import type { Region } from '@/lib/location'

export interface Dealer {
  id: string
  name: string
  tagline?: string
  flag?: string
  region: Region
  country: string
  website: string
  logo?: string
  description: string
  shipsTo: string[]
  currency: string
  currencySymbol: string
}

export interface Product {
  id: string
  dealerId: string
  name: string
  price: number
  currency: string
  currencySymbol: string
  starsPrice: number
  category: 'telescope' | 'eyepiece' | 'binocular' | 'accessory'
  description: string
  image: string
  externalUrl: string
  badge?: string
  specs?: Record<string, string>
  beginner?: boolean
  skillLevel?: 'beginner' | 'intermediate' | 'advanced'
}

const DEALERS: Dealer[] = [
  {
    id: 'astroman',
    name: 'Astroman',
    tagline: "Georgia's first astronomy store",
    flag: '🇬🇪',
    region: 'caucasus',
    country: 'GE',
    website: 'https://astroman.ge',
    description: "Georgia's first astronomy store — telescopes, gadgets & star maps",
    shipsTo: ['GE', 'AM', 'AZ', 'TR'],
    currency: 'GEL',
    currencySymbol: '₾',
  },
  {
    id: 'celestron-us',
    name: 'Celestron',
    tagline: "World's #1 telescope brand",
    flag: '🇺🇸',
    region: 'north_america',
    country: 'US',
    website: 'https://celestron.com',
    description: "World's #1 telescope brand — trusted by astronomers since 1960",
    shipsTo: ['US', 'CA'],
    currency: 'USD',
    currencySymbol: '$',
  },
  {
    id: 'levenhuk-eu',
    name: 'Levenhuk',
    tagline: "Telescopes for curious minds",
    flag: '🇪🇺',
    region: 'europe',
    country: 'EU',
    website: 'https://levenhuk.com',
    description: "European optics brand — telescopes, microscopes and accessories",
    shipsTo: ['DE','AT','CH','FR','IT','NL','BE','PL','ES','PT','SE','NO','DK','FI','CZ','HU','RO','GR','BG','HR','GB','IE','UA','LT','LV','EE'],
    currency: 'EUR',
    currencySymbol: '€',
  },
]

const PRODUCTS: Product[] = [
  // Astroman products
  {
    id: 'scope-bresser-76-300',
    dealerId: 'astroman',
    name: 'Bresser Junior 76/300 Compact',
    price: 288,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 2880,
    category: 'telescope',
    description: '76mm reflector, 300mm focal length. Compact and lightweight — ideal for beginners and young astronomers.',
    image: 'https://astroman.ge/wp-content/uploads/2024/11/222.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-bresser-50-360',
    dealerId: 'astroman',
    name: 'Bresser Junior 50/360 with Tent',
    price: 399,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 3990,
    category: 'telescope',
    description: '50mm refractor with pop-up observation tent. Perfect gift set for young astronomers.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/22122.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-natgeo-60-700',
    dealerId: 'astroman',
    name: 'National Geographic 60/700 AZ',
    price: 779,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 7790,
    category: 'telescope',
    description: '60mm refractor, 700mm focal length on alt-az mount. Great for Moon, planets, and terrestrial viewing.',
    image: 'https://astroman.ge/wp-content/uploads/2025/11/%E1%83%91%E1%83%94%E1%83%A5%E1%83%98-02.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-foreseen-80',
    dealerId: 'astroman',
    name: 'Foreseen 80mm Refractor',
    price: 856,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 8560,
    category: 'telescope',
    description: '80mm aperture refractor with sharp optics. Excellent planetary views and wide star fields.',
    image: 'https://astroman.ge/wp-content/uploads/2024/08/Telescope.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-natgeo-76-700',
    dealerId: 'astroman',
    name: 'National Geographic 76/700 Reflector',
    price: 788,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 7880,
    category: 'telescope',
    description: '76mm Newtonian reflector, 700mm focal length. Excellent light-gathering for deep-sky objects.',
    image: 'https://astroman.ge/wp-content/uploads/2024/08/0144181_national-geographic-114900-reflector-telescope-az_550.jpeg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-bresser-venus-76-700',
    dealerId: 'astroman',
    name: 'Bresser Venus 76/700 AZ',
    price: 998,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 9980,
    category: 'telescope',
    description: '76mm refractor with 700mm focal length on sturdy alt-az mount. Great all-rounder for visual observing.',
    image: 'https://astroman.ge/wp-content/uploads/2025/12/2221.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-celestron-70az',
    dealerId: 'astroman',
    name: 'Celestron AstroMaster 70AZ',
    price: 1258,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 12580,
    category: 'telescope',
    description: "Celestron's popular 70mm refractor on alt-az mount. Crystal-clear views of Moon and planets right out of the box.",
    image: 'https://astroman.ge/wp-content/uploads/2024/11/23312.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'scope-nexstar-90slt',
    dealerId: 'astroman',
    name: 'Celestron NexStar 90SLT',
    price: 2660,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 26600,
    category: 'telescope',
    description: '90mm computerized GoTo telescope with 4,000+ object database. Auto-aligns and tracks celestial objects.',
    image: 'https://astroman.ge/wp-content/uploads/2024/11/1222.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'advanced' as const,
  },
  {
    id: 'scope-starsense-dx6',
    dealerId: 'astroman',
    name: 'Celestron StarSense Explorer DX 6',
    price: 3998,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 39980,
    category: 'telescope',
    description: '150mm Newtonian with smartphone star-finding technology. Point your phone at the sky to locate objects.',
    image: 'https://astroman.ge/wp-content/uploads/2025/09/%E1%83%91%E1%83%94%E1%83%A5%E1%83%98-02.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'advanced' as const,
  },
  // Celestron (US) products — real data from celestron.com/collections/telescopes
  {
    id: 'cel-nexstar8se',
    dealerId: 'celestron-us',
    name: 'Celestron NexStar 8SE',
    price: 1699,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 16990,
    category: 'telescope',
    description: '8-inch Schmidt-Cassegrain with fully automated GoTo mount. 4,000+ object database, auto-align. The most popular telescope in America.',
    image: 'https://www.celestron.com/cdn/shop/files/RS15946_11069_NexStar_8SE_Computerized_Telescope_1-hpr.jpg?v=1728102013',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    badge: 'Best Seller',
    specs: { aperture: '203mm', focal: '2032mm', mount: 'GoTo Alt-Az' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'cel-nexstar6se',
    dealerId: 'celestron-us',
    name: 'Celestron NexStar 6SE',
    price: 1199,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 11990,
    category: 'telescope',
    description: '6-inch Schmidt-Cassegrain with computerized GoTo mount. Exceptional optics at a mid-range price point.',
    image: 'https://www.celestron.com/cdn/shop/products/050234110686_NexStar_6SE_11068_1.jpg?v=1727902053',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '150mm', focal: '1500mm', mount: 'GoTo Alt-Az' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'cel-starsense-dx130',
    dealerId: 'celestron-us',
    name: 'StarSense Explorer DX 130AZ',
    price: 499.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 4999,
    category: 'telescope',
    description: '130mm Newtonian reflector with smartphone star-finding technology. Point your phone at the sky and the app tells you exactly where to look.',
    image: 'https://www.celestron.com/cdn/shop/products/22461_StarSense_Explorer_DX_130_01.jpg?v=1727800326',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    badge: 'Popular',
    specs: { aperture: '130mm', focal: '650mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'cel-starsense-dx102',
    dealerId: 'celestron-us',
    name: 'StarSense Explorer DX 102AZ',
    price: 489.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 4899,
    category: 'telescope',
    description: '102mm refractor with phone-guided star-finding. App shows a live bullseye overlay to point at any object.',
    image: 'https://www.celestron.com/cdn/shop/products/22460_StarSense_Explorer_DX_102_01.jpg?v=1727800279',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '102mm', focal: '660mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'cel-starsense-lt114',
    dealerId: 'celestron-us',
    name: 'StarSense Explorer LT 114AZ',
    price: 259.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 2599,
    category: 'telescope',
    description: '114mm Newtonian with smartphone app navigation. Ideal first telescope — no alignment needed.',
    image: 'https://www.celestron.com/cdn/shop/products/22452_StarSense_Explorer_LT_114_01.jpg?v=1727800415',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '114mm', focal: '1000mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-travelscope80',
    dealerId: 'celestron-us',
    name: 'Celestron Travel Scope 80',
    price: 149.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 1499,
    category: 'telescope',
    description: 'Ultra-portable 80mm refractor with smartphone adapter. Fits in a backpack — perfect for travel and camping.',
    image: 'https://www.celestron.com/cdn/shop/products/22030_Travel_Scope_80_01_CallOut.jpg?v=1584998404',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '80mm', focal: '400mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  // Levenhuk (Europe) products
  {
    id: 'lev-blitz50',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Blitz 50 BASE',
    price: 59,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 590,
    category: 'telescope',
    description: '50mm refractor on alt-az mount. Perfect first telescope — simple, lightweight, easy to set up.',
    image: 'https://levenhuk.com/upload/iblock/7af/id7jw88sl3z22oq9s5ba0heubj72x6kl/77098_levenhuk-blitz-50-base-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-blitz-50-base-telescope/',
    specs: { aperture: '50mm', focal: '600mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-labzz-t2',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk LabZZ T2 Telescope',
    price: 49,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 490,
    category: 'telescope',
    description: '50mm kids telescope with compass, backpack, and book. Best astronomy gift for young astronomers.',
    image: 'https://levenhuk.com/upload/iblock/517/zhgfoqz7y5fh11rpanvpcz6h7mkocpbh/telescope-levenhuk-labzz-t2.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-labzz-t2-telescope/',
    specs: { aperture: '50mm', focal: '360mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-skyline-base70',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline BASE 70T',
    price: 89,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 890,
    category: 'telescope',
    description: '70mm tabletop refractor. Compact and sturdy — great for balconies and travel.',
    image: 'https://levenhuk.com/upload/iblock/e14/28uwnu7jh5dqnss1cc10mfv4x1hjopds/levenhuk-telescope-skyline-base-70t_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-base-70t-telescope/',
    specs: { aperture: '70mm', focal: '700mm', mount: 'Tabletop Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-travel70',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline Travel 70',
    price: 99,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 990,
    category: 'telescope',
    description: '70mm portable refractor with tripod. Folds into a compact bag — ideal for dark-sky trips.',
    image: 'https://levenhuk.com/upload/iblock/d83/qqj1uw6z8185jheis7g1cxi40gp3756k/levenhuk-telescope-skyline-travel-70_ZHSMksd.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-travel-70-telescope/',
    specs: { aperture: '70mm', focal: '700mm', mount: 'Travel Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-travel80',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline Travel 80',
    price: 119,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 1190,
    category: 'telescope',
    description: '80mm portable refractor. Wider aperture than the Travel 70 — better for star clusters.',
    image: 'https://levenhuk.com/upload/iblock/a1a/xbib0tgh954zo7ordwozonjh22i41p5y/levenhuk-telescope-skyline-travel-80_Lj59PQ2.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-travel-80-telescope/',
    specs: { aperture: '80mm', focal: '400mm', mount: 'Travel Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-base110',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline BASE 110S',
    price: 149,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 1490,
    category: 'telescope',
    description: '110mm reflector on simple mount. Step up from beginner scope — great light gathering.',
    image: 'https://levenhuk.com/upload/iblock/d52/75mtc25k6fr0pq0kudmga61l9g53lq6y/73800_levenhuk-telescope-skyline-base-110s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-base-110s-telescope/',
    specs: { aperture: '110mm', focal: '500mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-blitz114',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Blitz 114 PLUS',
    price: 179,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 1790,
    category: 'telescope',
    description: '114mm Newtonian reflector. Excellent for planets, Moon, and bright nebulae. Good upgrade scope.',
    image: 'https://levenhuk.com/upload/iblock/2a3/gy5w6ejd43sqplg89wpep1m5ghcibbg8/77106_levenhuk-blitz-114-plus-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-blitz-114-plus-telescope/',
    badge: 'Popular',
    specs: { aperture: '114mm', focal: '900mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-plus130',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PLUS 130S',
    price: 249,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 2490,
    category: 'telescope',
    description: '130mm Newtonian on EQ2 equatorial mount with 2 eyepieces and Barlow lens. Serious tracking for deep-sky.',
    image: 'https://levenhuk.com/upload/iblock/163/3fsyw807ft5mczvs22qd0olcqx02c3gr/levenhuk-telescope-skyline-plus-130s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-plus-130s-telescope/',
    badge: 'Best Seller',
    specs: { aperture: '130mm', focal: '900mm', mount: 'EQ2' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'lev-plus120',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PLUS 120S',
    price: 199,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 1990,
    category: 'telescope',
    description: '120mm short-tube Newtonian reflector. Excellent aperture for deep-sky objects — galaxies and nebulae.',
    image: 'https://levenhuk.com/upload/iblock/ef2/9k31l7bn9dbkazbpctyqbpt7iktpzmhv/73804_levenhuk-telescope-skyline-plus-120s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-plus-120s-telescope/',
    specs: { aperture: '120mm', focal: '600mm', mount: 'Manual Alt-Az' },
    skillLevel: 'advanced' as const,
  },

  // Astroman eyepieces & binoculars
  {
    id: 'astr-eyepiece-set',
    dealerId: 'astroman',
    name: 'Eyepiece Set (6mm + 20mm)',
    price: 119,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 1190,
    category: 'eyepiece',
    description: '1.25" eyepiece pair — 6mm for high magnification planets, 20mm for wide-field star clusters.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { barrel: '1.25"', qty: '2 eyepieces' },
  },
  {
    id: 'astr-bino-8x42',
    dealerId: 'astroman',
    name: 'Celestron UpClose G2 10x50',
    price: 349,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 3490,
    category: 'binocular',
    description: '10x50 binoculars — excellent for Milky Way sweeps, open clusters, comets, and birdwatching.',
    image: 'https://astroman.ge/wp-content/uploads/2024/11/23312.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { magnification: '10x', aperture: '50mm' },
  },
  // Celestron US eyepieces & binoculars
  {
    id: 'cel-xcel-7mm',
    dealerId: 'celestron-us',
    name: 'X-Cel LX 7mm Eyepiece',
    price: 59.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 599,
    category: 'eyepiece',
    description: '7mm X-Cel LX — 60° AFOV, fully multi-coated, parfocal. Ideal for planetary detail on Jupiter and Saturn.',
    image: 'https://www.celestron.com/cdn/shop/products/93420-X-Cel-LX.jpg?v=1590984285',
    externalUrl: 'https://www.celestron.com/products/x-cel-lx-7mm-eyepiece-125in',
    specs: { focal: '7mm', afov: '60°', barrel: '1.25"' },
  },
  {
    id: 'cel-xcel-18mm',
    dealerId: 'celestron-us',
    name: 'X-Cel LX 18mm Eyepiece',
    price: 59.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 599,
    category: 'eyepiece',
    description: '18mm X-Cel LX — wide-field views of star clusters and nebulae. Perfect companion to the 7mm.',
    image: 'https://www.celestron.com/cdn/shop/products/93425-X-Cel-LX.jpg?v=1590984289',
    externalUrl: 'https://www.celestron.com/products/x-cel-lx-18mm-eyepiece-125in',
    specs: { focal: '18mm', afov: '60°', barrel: '1.25"' },
  },
  {
    id: 'cel-upclose-10x50',
    dealerId: 'celestron-us',
    name: 'Celestron UpClose G2 10x50',
    price: 59.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 599,
    category: 'binocular',
    description: '10x50 binoculars with BK-7 prisms and multi-coated optics. Great for Milky Way, comets, and open clusters.',
    image: 'https://www.celestron.com/cdn/shop/products/050234252038_UpCloseG2_10x50_71256_01.jpg?v=1584999282',
    externalUrl: 'https://www.celestron.com/collections/binoculars',
    specs: { magnification: '10x', aperture: '50mm', prism: 'BK-7 Porro' },
  },
  {
    id: 'cel-skymaster-25x70',
    dealerId: 'celestron-us',
    name: 'Celestron SkyMaster 25x70',
    price: 109.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 1099,
    category: 'binocular',
    description: '25x70 giant binoculars — best for deep sky. Resolve star clusters, see Andromeda, and sweep the Milky Way.',
    image: 'https://www.celestron.com/cdn/shop/files/71008_skymaster_25x70_1.jpg?v=1765916800',
    externalUrl: 'https://www.celestron.com/collections/binoculars',
    badge: 'Best Seller',
    specs: { magnification: '25x', aperture: '70mm', prism: 'BaK-4 Porro' },
  },

  // Astroman — accessories, eyepieces, binoculars (12 more)
  {
    id: 'astr-bino-cometron-7x50',
    dealerId: 'astroman',
    name: 'Cometron 7x50 Binoculars',
    price: 269,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 2690,
    category: 'binocular',
    description: '7x50 wide-field binoculars. Bright views — great for Milky Way sweeps and finding deep-sky targets.',
    image: 'https://astroman.ge/wp-content/uploads/2024/11/23312.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { magnification: '7x', aperture: '50mm' },
  },
  {
    id: 'astr-bino-12x50',
    dealerId: 'astroman',
    name: 'Astro 12x50 Binoculars',
    price: 459,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 4590,
    category: 'binocular',
    description: '12x50 binoculars — higher magnification for Moon detail and double stars.',
    image: 'https://astroman.ge/wp-content/uploads/2024/11/23312.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { magnification: '12x', aperture: '50mm' },
  },
  {
    id: 'astr-eyepiece-plossl-25',
    dealerId: 'astroman',
    name: 'Plössl 25mm Eyepiece',
    price: 79,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 790,
    category: 'eyepiece',
    description: '1.25" Plössl 25mm — wide low-power eyepiece for star fields and finding objects.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { focal: '25mm', barrel: '1.25"' },
  },
  {
    id: 'astr-eyepiece-plossl-10',
    dealerId: 'astroman',
    name: 'Plössl 10mm Eyepiece',
    price: 79,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 790,
    category: 'eyepiece',
    description: '1.25" Plössl 10mm — high-power eyepiece for planets, Moon craters, and double stars.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { focal: '10mm', barrel: '1.25"' },
  },
  {
    id: 'astr-barlow-2x',
    dealerId: 'astroman',
    name: 'Barlow 2x Lens',
    price: 89,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 890,
    category: 'accessory',
    description: '1.25" Barlow lens — doubles the magnification of any eyepiece. Essential for serious planetary observing.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { type: 'Barlow', factor: '2x', barrel: '1.25"' },
  },
  {
    id: 'astr-moon-filter',
    dealerId: 'astroman',
    name: 'Moon Filter 1.25"',
    price: 39,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 390,
    category: 'accessory',
    description: 'Neutral density filter — reduces Moon glare so you can see crater detail without eye fatigue.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { thread: '1.25"', density: 'ND-13%' },
  },
  {
    id: 'astr-solar-filter',
    dealerId: 'astroman',
    name: 'Universal Solar Filter',
    price: 149,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 1490,
    category: 'accessory',
    description: 'Baader-style solar film filter for safe daytime Sun observing. Resize to fit any 60–120mm telescope.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { type: 'Solar film', density: 'ND-5' },
  },
  {
    id: 'astr-smartphone-adapter',
    dealerId: 'astroman',
    name: 'Smartphone Telescope Adapter',
    price: 69,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 690,
    category: 'accessory',
    description: 'Universal phone mount that clamps to any 1.25" eyepiece. Capture the Moon and planets through your scope.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { type: 'Phone adapter', barrel: '1.25"' },
  },
  {
    id: 'astr-star-atlas',
    dealerId: 'astroman',
    name: 'Pocket Star Atlas (KA)',
    price: 49,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 490,
    category: 'accessory',
    description: 'Georgian-language pocket star atlas. Constellation maps, deep-sky objects, monthly sky charts.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { language: 'Georgian', pages: '96' },
  },
  {
    id: 'astr-planisphere',
    dealerId: 'astroman',
    name: 'Star Planisphere 40°N',
    price: 35,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 350,
    category: 'accessory',
    description: 'Rotating star map for 40°N latitude (Tbilisi, Yerevan, Istanbul). Shows what stars are up at any date and time.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { latitude: '40°N' },
  },
  {
    id: 'astr-red-flashlight',
    dealerId: 'astroman',
    name: 'Red Astronomy Flashlight',
    price: 29,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 290,
    category: 'accessory',
    description: 'Dim red LED flashlight. Reads charts and finds gear without ruining your dark-adapted vision.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { led: 'Red', battery: 'AAA x2' },
  },
  {
    id: 'astr-telescope-bag',
    dealerId: 'astroman',
    name: 'Padded Telescope Carry Bag',
    price: 159,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 1590,
    category: 'accessory',
    description: 'Padded carry bag for travel telescopes up to 80mm. Foam-lined with strap and side pocket for eyepieces.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { fit: 'up to 80mm' },
  },

  // Celestron US — additional telescopes, accessories (10 more)
  {
    id: 'cel-astromaster-130eq',
    dealerId: 'celestron-us',
    name: 'Celestron AstroMaster 130EQ',
    price: 449.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 4499,
    category: 'telescope',
    description: '130mm Newtonian on equatorial mount. Bright deep-sky views with manual tracking. Classic first serious telescope.',
    image: 'https://www.celestron.com/cdn/shop/files/RS15946_11069_NexStar_8SE_Computerized_Telescope_1-hpr.jpg?v=1728102013',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '130mm', focal: '650mm', mount: 'EQ-2 Equatorial' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'cel-powerseeker-127eq',
    dealerId: 'celestron-us',
    name: 'Celestron PowerSeeker 127EQ',
    price: 229.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 2299,
    category: 'telescope',
    description: '127mm reflector on equatorial mount. Great budget aperture for the Moon, planets, and brighter deep-sky.',
    image: 'https://www.celestron.com/cdn/shop/products/22452_StarSense_Explorer_LT_114_01.jpg?v=1727800415',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '127mm', focal: '1000mm', mount: 'EQ-2' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-firstscope',
    dealerId: 'celestron-us',
    name: 'Celestron FirstScope 76',
    price: 79.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 799,
    category: 'telescope',
    description: '76mm tabletop Dobsonian. Tiny footprint, point-and-look simplicity. Honored by IAU as a great first scope.',
    image: 'https://www.celestron.com/cdn/shop/products/22030_Travel_Scope_80_01_CallOut.jpg?v=1584998404',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '76mm', focal: '300mm', mount: 'Tabletop Dobsonian' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-omni-xlt-150',
    dealerId: 'celestron-us',
    name: 'Celestron Omni XLT 150',
    price: 999,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 9990,
    category: 'telescope',
    description: '150mm Newtonian on Omni CG-4 equatorial mount with StarBright XLT coatings. Serious mid-range scope.',
    image: 'https://www.celestron.com/cdn/shop/products/050234110686_NexStar_6SE_11068_1.jpg?v=1727902053',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '150mm', focal: '750mm', mount: 'CG-4 Equatorial' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'cel-skyprodigy-130',
    dealerId: 'celestron-us',
    name: 'Celestron SkyProdigy 130',
    price: 899,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 8990,
    category: 'telescope',
    description: '130mm computerized Newtonian with StarSense auto-align — points itself with the press of a button.',
    image: 'https://www.celestron.com/cdn/shop/products/22461_StarSense_Explorer_DX_130_01.jpg?v=1727800326',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '130mm', focal: '650mm', mount: 'GoTo Alt-Az' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'cel-zoom-eyepiece',
    dealerId: 'celestron-us',
    name: 'Celestron 8-24mm Zoom Eyepiece',
    price: 79.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 799,
    category: 'eyepiece',
    description: 'Variable 8–24mm zoom eyepiece. One-piece replacement for an entire eyepiece set — twist to change power.',
    image: 'https://www.celestron.com/cdn/shop/products/93420-X-Cel-LX.jpg?v=1590984285',
    externalUrl: 'https://www.celestron.com/collections/eyepieces',
    specs: { focal: '8-24mm', barrel: '1.25"' },
  },
  {
    id: 'cel-omni-eyepiece-12',
    dealerId: 'celestron-us',
    name: 'Celestron Omni 12mm Plössl',
    price: 39.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 399,
    category: 'eyepiece',
    description: '12mm Plössl eyepiece — sharp images, multi-coated optics. A reliable workhorse for any 1.25" telescope.',
    image: 'https://www.celestron.com/cdn/shop/products/93425-X-Cel-LX.jpg?v=1590984289',
    externalUrl: 'https://www.celestron.com/collections/eyepieces',
    specs: { focal: '12mm', afov: '50°', barrel: '1.25"' },
  },
  {
    id: 'cel-skymaster-15x70',
    dealerId: 'celestron-us',
    name: 'Celestron SkyMaster 15x70',
    price: 89.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 899,
    category: 'binocular',
    description: '15x70 astronomy binoculars — the favorite first deep-sky instrument. Great for Andromeda and clusters.',
    image: 'https://www.celestron.com/cdn/shop/files/71008_skymaster_25x70_1.jpg?v=1765916800',
    externalUrl: 'https://www.celestron.com/collections/binoculars',
    specs: { magnification: '15x', aperture: '70mm', prism: 'BaK-4 Porro' },
  },
  {
    id: 'cel-nature-dx-8x42',
    dealerId: 'celestron-us',
    name: 'Celestron Nature DX 8x42',
    price: 159.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 1599,
    category: 'binocular',
    description: '8x42 roof-prism binoculars. Excellent for daytime nature use and casual stargazing — fully waterproof.',
    image: 'https://www.celestron.com/cdn/shop/products/050234252038_UpCloseG2_10x50_71256_01.jpg?v=1584999282',
    externalUrl: 'https://www.celestron.com/collections/binoculars',
    specs: { magnification: '8x', aperture: '42mm', prism: 'BaK-4 Roof' },
  },
  {
    id: 'cel-nexyz-adapter',
    dealerId: 'celestron-us',
    name: 'Celestron NexYZ Smartphone Adapter',
    price: 64.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 649,
    category: 'accessory',
    description: '3-axis universal phone mount. Precise X/Y/Z alignment to any eyepiece — capture the Moon and planets.',
    image: 'https://www.celestron.com/cdn/shop/products/93420-X-Cel-LX.jpg?v=1590984285',
    externalUrl: 'https://www.celestron.com/products/nexyz-3-axis-universal-smartphone-adapter',
    specs: { type: 'Phone adapter', axes: '3' },
  },

  // Levenhuk EU — additional telescopes (12 more)
  {
    id: 'lev-skyline-base-90',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline BASE 90T',
    price: 129,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 1290,
    category: 'telescope',
    description: '90mm refractor on alt-az mount. Sharp planetary views and a wide enough field for star clusters.',
    image: 'https://levenhuk.com/upload/iblock/e14/28uwnu7jh5dqnss1cc10mfv4x1hjopds/levenhuk-telescope-skyline-base-70t_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    specs: { aperture: '90mm', focal: '900mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-skyline-pro-127-mak',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PRO 127 MAK',
    price: 549,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 5490,
    category: 'telescope',
    description: '127mm Maksutov-Cassegrain — sharp, high-contrast planetary views in a compact tube. Premium glass.',
    image: 'https://levenhuk.com/upload/iblock/163/3fsyw807ft5mczvs22qd0olcqx02c3gr/levenhuk-telescope-skyline-plus-130s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    badge: 'Premium',
    specs: { aperture: '127mm', focal: '1500mm', mount: 'EQ' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'lev-strike-90-plus',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Strike 90 PLUS',
    price: 159,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 1590,
    category: 'telescope',
    description: '90mm refractor full kit — eyepieces, Barlow, Moon filter, smartphone adapter, and book all included.',
    image: 'https://levenhuk.com/upload/iblock/2a3/gy5w6ejd43sqplg89wpep1m5ghcibbg8/77106_levenhuk-blitz-114-plus-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    specs: { aperture: '90mm', focal: '600mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-blitz-60-base',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Blitz 60 BASE',
    price: 69,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 690,
    category: 'telescope',
    description: '60mm refractor on simple alt-az mount. Step up from a 50mm — bigger, brighter views of Moon and planets.',
    image: 'https://levenhuk.com/upload/iblock/7af/id7jw88sl3z22oq9s5ba0heubj72x6kl/77098_levenhuk-blitz-50-base-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    specs: { aperture: '60mm', focal: '700mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-blitz-70-plus',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Blitz 70 PLUS',
    price: 99,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 990,
    category: 'telescope',
    description: '70mm refractor full kit. Everything you need for a first night out — eyepieces, Barlow, smartphone adapter.',
    image: 'https://levenhuk.com/upload/iblock/2a3/gy5w6ejd43sqplg89wpep1m5ghcibbg8/77106_levenhuk-blitz-114-plus-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    specs: { aperture: '70mm', focal: '700mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-blitz-90-plus',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Blitz 90 PLUS',
    price: 219,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 2190,
    category: 'telescope',
    description: '90mm Newtonian reflector kit. Wide aperture for nebulae and brighter galaxies. Includes accessory pack.',
    image: 'https://levenhuk.com/upload/iblock/2a3/gy5w6ejd43sqplg89wpep1m5ghcibbg8/77106_levenhuk-blitz-114-plus-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    specs: { aperture: '90mm', focal: '900mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-skyline-base-100',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline BASE 100',
    price: 139,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 1390,
    category: 'telescope',
    description: '100mm reflector on alt-az mount. Solid step-up scope — much more aperture than the 70 and 80 series.',
    image: 'https://levenhuk.com/upload/iblock/d52/75mtc25k6fr0pq0kudmga61l9g53lq6y/73800_levenhuk-telescope-skyline-base-110s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    specs: { aperture: '100mm', focal: '500mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-skyline-base-80t',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline BASE 80T',
    price: 109,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 1090,
    category: 'telescope',
    description: '80mm tabletop refractor. Sturdy short-tube design — easy to set up and take to a balcony or rooftop.',
    image: 'https://levenhuk.com/upload/iblock/e14/28uwnu7jh5dqnss1cc10mfv4x1hjopds/levenhuk-telescope-skyline-base-70t_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    specs: { aperture: '80mm', focal: '400mm', mount: 'Tabletop Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-skyline-pro-90-mak',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PRO 90 MAK',
    price: 379,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 3790,
    category: 'telescope',
    description: '90mm Maksutov-Cassegrain. Compact, sharp planetary scope with premium glass and long focal length.',
    image: 'https://levenhuk.com/upload/iblock/163/3fsyw807ft5mczvs22qd0olcqx02c3gr/levenhuk-telescope-skyline-plus-130s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    specs: { aperture: '90mm', focal: '1250mm', mount: 'EQ' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'lev-skyline-pro-130-eq',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PRO 130 EQ',
    price: 289,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 2890,
    category: 'telescope',
    description: '130mm Newtonian on equatorial mount with motor drive. Tracks objects across the sky — astrophoto ready.',
    image: 'https://levenhuk.com/upload/iblock/ef2/9k31l7bn9dbkazbpctyqbpt7iktpzmhv/73804_levenhuk-telescope-skyline-plus-120s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    specs: { aperture: '130mm', focal: '650mm', mount: 'EQ-2' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'lev-skyline-base-120',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline BASE 120',
    price: 219,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 2190,
    category: 'telescope',
    description: '120mm reflector — large aperture at a fair price. Resolves brighter galaxies and faint nebulae.',
    image: 'https://levenhuk.com/upload/iblock/ef2/9k31l7bn9dbkazbpctyqbpt7iktpzmhv/73804_levenhuk-telescope-skyline-plus-120s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    specs: { aperture: '120mm', focal: '600mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-skyline-pro-150',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PRO 150',
    price: 379,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 3790,
    category: 'telescope',
    description: '150mm Newtonian — serious aperture for deep-sky. Galaxies, nebulae, and globular clusters come alive.',
    image: 'https://levenhuk.com/upload/iblock/163/3fsyw807ft5mczvs22qd0olcqx02c3gr/levenhuk-telescope-skyline-plus-130s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/',
    badge: 'Best Aperture',
    specs: { aperture: '150mm', focal: '750mm', mount: 'EQ' },
    skillLevel: 'advanced' as const,
  },
]

// Global fallback: 2 telescopes each from Astroman, Celestron, and Levenhuk
function buildGlobalFallback(): Product[] {
  const ids = ['astroman', 'celestron-us', 'levenhuk-eu']
  return ids.flatMap((id) =>
    PRODUCTS.filter((p) => p.dealerId === id && p.category === 'telescope')
      .sort((a, b) => a.price - b.price)
      .slice(0, 2)
  )
}

export const GLOBAL_FALLBACK = buildGlobalFallback()

export function getDealersByRegion(region: Region): Dealer[] {
  if (region === 'global') return DEALERS
  if (region === 'asia') return DEALERS.filter((d) => d.id === 'astroman')
  if (region === 'south_america') return DEALERS.filter((d) => d.id === 'celestron-us')
  return DEALERS.filter((d) => d.region === region)
}

export function getProductsByRegion(region: Region): Product[] {
  if (region === 'global') return GLOBAL_FALLBACK
  if (region === 'asia') return PRODUCTS.filter((p) => p.dealerId === 'astroman')
  if (region === 'south_america') return PRODUCTS.filter((p) => p.dealerId === 'celestron-us')
  const dealerIds = getDealersByRegion(region).map((d) => d.id)
  return PRODUCTS.filter((p) => dealerIds.includes(p.dealerId))
}

export function getDealerById(id: string): Dealer | undefined {
  return DEALERS.find((d) => d.id === id)
}

export function getProductsByDealer(dealerId: string): Product[] {
  return PRODUCTS.filter((p) => p.dealerId === dealerId)
}

export function getAllDealers(): Dealer[] {
  return DEALERS
}
