import type { Region } from '@/lib/location'
import { computeMarketplaceStarsPrice } from '@/lib/stars-economy'

export interface Dealer {
  id: string
  name: string
  tagline?: string
  flag?: string
  region: Region
  country: string
  website: string
  logo?: string
  description: string
  shipsTo: string[]
  currency: string
  currencySymbol: string
}

export interface Product {
  id: string
  dealerId: string
  name: string
  price: number
  currency: string
  currencySymbol: string
  starsPrice: number
  category: 'telescope' | 'eyepiece' | 'binocular' | 'accessory'
  description: string
  image: string
  externalUrl: string
  badge?: string
  specs?: Record<string, string>
  beginner?: boolean
  skillLevel?: 'beginner' | 'intermediate' | 'advanced'
  /**
   * 'stars-only' marks an item that is sold exclusively in the in-app Star
   * Shop — the user pays with the Stars SPL token, no SOL / fiat. Default
   * (undefined) means the item shows in the regular SOL / Stars dual-price
   * marketplace.
   */
  kind?: 'stars-only'
  /** Hand-picked for the "Featured Deals" rail. Set via FEATURED_IDS. */
  featured?: boolean
  /** Hand-picked for the "Recommended for You" rail. Set via RECOMMENDED_IDS. */
  recommended?: boolean
  /** Editorial rating (1–5) for prominently merchandised gear. Set via RATINGS. */
  rating?: number
  /** Review count paired with `rating`. Set via RATINGS. */
  reviews?: number
}

const DEALERS: Dealer[] = [
  {
    id: 'astroman',
    name: 'Astroman',
    tagline: "Georgia's first astronomy store",
    flag: '🇬🇪',
    region: 'caucasus',
    country: 'GE',
    website: 'https://astroman.ge',
    description: "Georgia's first astronomy store — telescopes, gadgets & star maps",
    shipsTo: ['GE', 'AM', 'AZ', 'TR'],
    currency: 'GEL',
    currencySymbol: '₾',
  },
  {
    id: 'celestron-us',
    name: 'Celestron',
    tagline: "World's #1 telescope brand",
    flag: '🇺🇸',
    region: 'north_america',
    country: 'US',
    website: 'https://celestron.com',
    description: "World's #1 telescope brand — trusted by astronomers since 1960",
    shipsTo: ['US', 'CA'],
    currency: 'USD',
    currencySymbol: '$',
  },
  {
    id: 'levenhuk-eu',
    name: 'Levenhuk',
    tagline: "Telescopes for curious minds",
    flag: '🇪🇺',
    region: 'europe',
    country: 'EU',
    website: 'https://levenhuk.com',
    description: "European optics brand — telescopes, microscopes and accessories",
    shipsTo: ['DE','AT','CH','FR','IT','NL','BE','PL','ES','PT','SE','NO','DK','FI','CZ','HU','RO','GR','BG','HR','GB','IE','UA','LT','LV','EE'],
    currency: 'EUR',
    currencySymbol: '€',
  },
  {
    id: 'bresser-eu',
    name: 'Bresser',
    tagline: 'German optics since 1957',
    flag: '🇩🇪',
    region: 'europe',
    country: 'DE',
    website: 'https://www.bresser.com',
    description: 'German optics house — telescopes, binoculars & the National Geographic optics line',
    shipsTo: ['DE','AT','CH','FR','IT','NL','BE','PL','ES','PT','SE','NO','DK','FI','CZ','HU','RO','GR','BG','HR','GB','IE','UA','LT','LV','EE'],
    currency: 'EUR',
    currencySymbol: '€',
  },
]

const PRODUCTS: Product[] = [
  // Astroman products
  {
    id: 'scope-bresser-76-300',
    dealerId: 'astroman',
    name: 'Bresser Junior 76/300 Compact',
    price: 288,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 28800,
    category: 'telescope',
    description: '76mm reflector, 300mm focal length. Compact and lightweight — ideal for beginners and young astronomers.',
    image: 'https://astroman.ge/wp-content/uploads/2024/11/222.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-bresser-50-360',
    dealerId: 'astroman',
    name: 'Bresser Junior 50/360 with Tent',
    price: 399,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 39900,
    category: 'telescope',
    description: '50mm refractor with pop-up observation tent. Perfect gift set for young astronomers.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/22122.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-natgeo-60-700',
    dealerId: 'astroman',
    name: 'National Geographic 60/700 AZ',
    price: 779,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 77900,
    category: 'telescope',
    description: '60mm refractor, 700mm focal length on alt-az mount. Great for Moon, planets, and terrestrial viewing.',
    image: 'https://astroman.ge/wp-content/uploads/2025/11/%E1%83%91%E1%83%94%E1%83%A5%E1%83%98-02.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-foreseen-80',
    dealerId: 'astroman',
    name: 'Foreseen 80mm Refractor',
    price: 856,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 85600,
    category: 'telescope',
    description: '80mm aperture refractor with sharp optics. Excellent planetary views and wide star fields.',
    image: 'https://astroman.ge/wp-content/uploads/2024/08/Telescope.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-natgeo-76-700',
    dealerId: 'astroman',
    name: 'National Geographic 76/700 Reflector',
    price: 788,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 78800,
    category: 'telescope',
    description: '76mm Newtonian reflector, 700mm focal length. Excellent light-gathering for deep-sky objects.',
    image: 'https://astroman.ge/wp-content/uploads/2024/08/0144181_national-geographic-114900-reflector-telescope-az_550.jpeg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-bresser-venus-76-700',
    dealerId: 'astroman',
    name: 'Bresser Venus 76/700 AZ',
    price: 998,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 99800,
    category: 'telescope',
    description: '76mm refractor with 700mm focal length on sturdy alt-az mount. Great all-rounder for visual observing.',
    image: 'https://astroman.ge/wp-content/uploads/2025/12/2221.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'scope-celestron-70az',
    dealerId: 'astroman',
    name: 'Celestron AstroMaster 70AZ',
    price: 1258,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 125800,
    category: 'telescope',
    description: "Celestron's popular 70mm refractor on alt-az mount. Crystal-clear views of Moon and planets right out of the box.",
    image: 'https://astroman.ge/wp-content/uploads/2024/11/23312.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'scope-nexstar-90slt',
    dealerId: 'astroman',
    name: 'Celestron NexStar 90SLT',
    price: 2660,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 266000,
    category: 'telescope',
    description: '90mm computerized GoTo telescope with 4,000+ object database. Auto-aligns and tracks celestial objects.',
    image: 'https://astroman.ge/wp-content/uploads/2024/11/1222.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'advanced' as const,
  },
  {
    id: 'scope-starsense-dx6',
    dealerId: 'astroman',
    name: 'Celestron StarSense Explorer DX 6',
    price: 3998,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 399800,
    category: 'telescope',
    description: '150mm Newtonian with smartphone star-finding technology. Point your phone at the sky to locate objects.',
    image: 'https://astroman.ge/wp-content/uploads/2025/09/%E1%83%91%E1%83%94%E1%83%A5%E1%83%98-02.jpg',
    externalUrl: 'https://astroman.ge/teleskopi/',
    skillLevel: 'advanced' as const,
  },
  // Celestron (US) products — real data from celestron.com/collections/telescopes
  {
    id: 'cel-nexstar8se',
    dealerId: 'celestron-us',
    name: 'Celestron NexStar 8SE',
    price: 1699,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 465526,
    category: 'telescope',
    description: '8-inch Schmidt-Cassegrain with fully automated GoTo mount. 4,000+ object database, auto-align. The most popular telescope in America.',
    image: 'https://www.celestron.com/cdn/shop/files/RS15946_11069_NexStar_8SE_Computerized_Telescope_1-hpr.jpg?v=1728102013',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    badge: 'Best Seller',
    specs: { aperture: '203mm', focal: '2032mm', mount: 'GoTo Alt-Az' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'cel-nexstar6se',
    dealerId: 'celestron-us',
    name: 'Celestron NexStar 6SE',
    price: 1199,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 328526,
    category: 'telescope',
    description: '6-inch Schmidt-Cassegrain with computerized GoTo mount. Exceptional optics at a mid-range price point.',
    image: 'https://www.celestron.com/cdn/shop/products/050234110686_NexStar_6SE_11068_1.jpg?v=1727902053',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '150mm', focal: '1500mm', mount: 'GoTo Alt-Az' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'cel-starsense-dx130',
    dealerId: 'celestron-us',
    name: 'StarSense Explorer DX 130AZ',
    price: 499.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 136986,
    category: 'telescope',
    description: '130mm Newtonian reflector with smartphone star-finding technology. Point your phone at the sky and the app tells you exactly where to look.',
    image: 'https://www.celestron.com/cdn/shop/products/22461_StarSense_Explorer_DX_130_01.jpg?v=1727800326',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    badge: 'Popular',
    specs: { aperture: '130mm', focal: '650mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'cel-starsense-dx102',
    dealerId: 'celestron-us',
    name: 'StarSense Explorer DX 102AZ',
    price: 489.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 134246,
    category: 'telescope',
    description: '102mm refractor with phone-guided star-finding. App shows a live bullseye overlay to point at any object.',
    image: 'https://www.celestron.com/cdn/shop/products/22460_StarSense_Explorer_DX_102_01.jpg?v=1727800279',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '102mm', focal: '660mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'cel-starsense-lt114',
    dealerId: 'celestron-us',
    name: 'StarSense Explorer LT 114AZ',
    price: 259.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 71226,
    category: 'telescope',
    description: '114mm Newtonian with smartphone app navigation. Ideal first telescope — no alignment needed.',
    image: 'https://www.celestron.com/cdn/shop/products/22452_StarSense_Explorer_LT_114_01.jpg?v=1727800415',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '114mm', focal: '1000mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-travelscope80',
    dealerId: 'celestron-us',
    name: 'Celestron Travel Scope 80',
    price: 149.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 41086,
    category: 'telescope',
    description: 'Ultra-portable 80mm refractor with smartphone adapter. Fits in a backpack — perfect for travel and camping.',
    image: 'https://www.celestron.com/cdn/shop/products/22030_Travel_Scope_80_01_CallOut.jpg?v=1584998404',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '80mm', focal: '400mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  // Levenhuk (Europe) products
  {
    id: 'lev-blitz50',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Blitz 50 BASE',
    price: 59,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 17464,
    category: 'telescope',
    description: '50mm refractor on alt-az mount. Perfect first telescope — simple, lightweight, easy to set up.',
    image: 'https://levenhuk.com/upload/iblock/7af/id7jw88sl3z22oq9s5ba0heubj72x6kl/77098_levenhuk-blitz-50-base-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-blitz-50-base-telescope/',
    specs: { aperture: '50mm', focal: '600mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-labzz-t2',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk LabZZ T2 Telescope',
    price: 49,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 14504,
    category: 'telescope',
    description: '50mm kids telescope with compass, backpack, and book. Best astronomy gift for young astronomers.',
    image: 'https://levenhuk.com/upload/iblock/517/zhgfoqz7y5fh11rpanvpcz6h7mkocpbh/telescope-levenhuk-labzz-t2.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-labzz-t2-telescope/',
    specs: { aperture: '50mm', focal: '360mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-skyline-base70',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline BASE 70T',
    price: 89,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 26344,
    category: 'telescope',
    description: '70mm tabletop refractor. Compact and sturdy — great for balconies and travel.',
    image: 'https://levenhuk.com/upload/iblock/e14/28uwnu7jh5dqnss1cc10mfv4x1hjopds/levenhuk-telescope-skyline-base-70t_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-base-70t-telescope/',
    specs: { aperture: '70mm', focal: '700mm', mount: 'Tabletop Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-travel70',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline Travel 70',
    price: 99,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 29304,
    category: 'telescope',
    description: '70mm portable refractor with tripod. Folds into a compact bag — ideal for dark-sky trips.',
    image: 'https://levenhuk.com/upload/iblock/d83/qqj1uw6z8185jheis7g1cxi40gp3756k/levenhuk-telescope-skyline-travel-70_ZHSMksd.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-travel-70-telescope/',
    specs: { aperture: '70mm', focal: '700mm', mount: 'Travel Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-travel80',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline Travel 80',
    price: 119,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 35224,
    category: 'telescope',
    description: '80mm portable refractor. Wider aperture than the Travel 70 — better for star clusters.',
    image: 'https://levenhuk.com/upload/iblock/a1a/xbib0tgh954zo7ordwozonjh22i41p5y/levenhuk-telescope-skyline-travel-80_Lj59PQ2.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-travel-80-telescope/',
    specs: { aperture: '80mm', focal: '400mm', mount: 'Travel Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-base110',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline BASE 110S',
    price: 149,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 44104,
    category: 'telescope',
    description: '110mm reflector on simple mount. Step up from beginner scope — great light gathering.',
    image: 'https://levenhuk.com/upload/iblock/d52/75mtc25k6fr0pq0kudmga61l9g53lq6y/73800_levenhuk-telescope-skyline-base-110s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-base-110s-telescope/',
    specs: { aperture: '110mm', focal: '500mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-blitz114',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Blitz 114 PLUS',
    price: 179,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 52984,
    category: 'telescope',
    description: '114mm Newtonian reflector. Excellent for planets, Moon, and bright nebulae. Good upgrade scope.',
    image: 'https://levenhuk.com/upload/iblock/2a3/gy5w6ejd43sqplg89wpep1m5ghcibbg8/77106_levenhuk-blitz-114-plus-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-blitz-114-plus-telescope/',
    badge: 'Popular',
    specs: { aperture: '114mm', focal: '900mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-plus130',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PLUS 130S',
    price: 249,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 73704,
    category: 'telescope',
    description: '130mm Newtonian on EQ2 equatorial mount with 2 eyepieces and Barlow lens. Serious tracking for deep-sky.',
    image: 'https://levenhuk.com/upload/iblock/163/3fsyw807ft5mczvs22qd0olcqx02c3gr/levenhuk-telescope-skyline-plus-130s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-plus-130s-telescope/',
    badge: 'Best Seller',
    specs: { aperture: '130mm', focal: '900mm', mount: 'EQ2' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'lev-plus120',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PLUS 120S',
    price: 199,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 58904,
    category: 'telescope',
    description: '120mm short-tube Newtonian reflector. Excellent aperture for deep-sky objects — galaxies and nebulae.',
    image: 'https://levenhuk.com/upload/iblock/ef2/9k31l7bn9dbkazbpctyqbpt7iktpzmhv/73804_levenhuk-telescope-skyline-plus-120s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-plus-120s-telescope/',
    specs: { aperture: '120mm', focal: '600mm', mount: 'Manual Alt-Az' },
    skillLevel: 'advanced' as const,
  },

  // Astroman eyepieces & binoculars
  {
    id: 'astr-eyepiece-set',
    dealerId: 'astroman',
    name: 'Eyepiece Set (6mm + 20mm)',
    price: 119,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 11900,
    category: 'eyepiece',
    description: '1.25" eyepiece pair — 6mm for high magnification planets, 20mm for wide-field star clusters.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { barrel: '1.25"', qty: '2 eyepieces' },
  },
  {
    id: 'astr-bino-8x42',
    dealerId: 'astroman',
    name: 'Celestron UpClose G2 10x50',
    price: 349,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 34900,
    category: 'binocular',
    description: '10x50 binoculars — excellent for Milky Way sweeps, open clusters, comets, and birdwatching.',
    image: 'https://astroman.ge/wp-content/uploads/2024/11/23312.jpg',
    externalUrl: 'https://astroman.ge/aksesuar/',
    specs: { magnification: '10x', aperture: '50mm' },
  },
  // Celestron US eyepieces & binoculars
  {
    id: 'cel-xcel-7mm',
    dealerId: 'celestron-us',
    name: 'X-Cel LX 7mm Eyepiece',
    price: 59.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 16426,
    category: 'eyepiece',
    description: '7mm X-Cel LX — 60° AFOV, fully multi-coated, parfocal. Ideal for planetary detail on Jupiter and Saturn.',
    image: 'https://www.celestron.com/cdn/shop/products/93420-X-Cel-LX.jpg?v=1590984285',
    externalUrl: 'https://www.celestron.com/products/x-cel-lx-7mm-eyepiece-125in',
    specs: { focal: '7mm', afov: '60°', barrel: '1.25"' },
  },
  {
    id: 'cel-xcel-18mm',
    dealerId: 'celestron-us',
    name: 'X-Cel LX 18mm Eyepiece',
    price: 59.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 16426,
    category: 'eyepiece',
    description: '18mm X-Cel LX — wide-field views of star clusters and nebulae. Perfect companion to the 7mm.',
    image: 'https://www.celestron.com/cdn/shop/products/93425-X-Cel-LX.jpg?v=1590984289',
    externalUrl: 'https://www.celestron.com/products/x-cel-lx-18mm-eyepiece-125in',
    specs: { focal: '18mm', afov: '60°', barrel: '1.25"' },
  },
  {
    id: 'cel-upclose-10x50',
    dealerId: 'celestron-us',
    name: 'Celestron UpClose G2 10x50',
    price: 59.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 16426,
    category: 'binocular',
    description: '10x50 binoculars with BK-7 prisms and multi-coated optics. Great for Milky Way, comets, and open clusters.',
    image: 'https://www.celestron.com/cdn/shop/products/050234712569_UpClose_G2_10x50_Porro_Box_71256_1.jpg',
    externalUrl: 'https://www.celestron.com/collections/binoculars',
    specs: { magnification: '10x', aperture: '50mm', prism: 'BK-7 Porro' },
  },
  {
    id: 'cel-skymaster-25x70',
    dealerId: 'celestron-us',
    name: 'Celestron SkyMaster 25x70',
    price: 109.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 30126,
    category: 'binocular',
    description: '25x70 giant binoculars — best for deep sky. Resolve star clusters, see Andromeda, and sweep the Milky Way.',
    image: 'https://www.celestron.com/cdn/shop/files/71008_skymaster_25x70_1.jpg?v=1765916800',
    externalUrl: 'https://www.celestron.com/collections/binoculars',
    badge: 'Best Seller',
    specs: { magnification: '25x', aperture: '70mm', prism: 'BaK-4 Porro' },
  },

  // Astroman — real catalog products with verified images from astroman.ge
  {
    id: 'astr-travel-scope-50',
    dealerId: 'astroman',
    name: 'Travel Scope 50mm',
    price: 169,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 16900,
    category: 'telescope',
    description: 'Compact 50mm travel telescope. Folds into a small bag — perfect for road trips and dark-sky weekends.',
    image: 'https://astroman.ge/wp-content/uploads/2025/12/Document-1.jpg',
    externalUrl: 'https://astroman.ge/travel-scope-50mm/',
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'astr-celestron-travel-70-dx',
    dealerId: 'astroman',
    name: 'Celestron Travel Scope 70 DX',
    price: 1098,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 109800,
    category: 'telescope',
    description: '70mm portable refractor with smartphone adapter and full backpack. Fits in carry-on luggage.',
    image: 'https://astroman.ge/wp-content/uploads/2024/11/ბექი-02.jpg',
    externalUrl: 'https://astroman.ge/celestron-travel-scope-70-dx/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'astr-firstscope-moon',
    dealerId: 'astroman',
    name: 'Telescope FirstScope Moon',
    price: 269,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 26900,
    category: 'telescope',
    description: 'Tabletop Moon-finder. Compact and intuitive — point and look. Great gift for kids and beginners.',
    image: 'https://astroman.ge/wp-content/uploads/2024/11/22.jpg',
    externalUrl: 'https://astroman.ge/teleskopi-firstscope-moon/',
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'astr-natgeo-45-600',
    dealerId: 'astroman',
    name: 'National Geographic 45/600 AZ',
    price: 489,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 48900,
    category: 'telescope',
    description: '45mm refractor on alt-azimuth mount. Solid first telescope for the Moon and bright planets.',
    image: 'https://astroman.ge/wp-content/uploads/2023/11/ბექი-02.jpg',
    externalUrl: 'https://astroman.ge/national-geographic-50-600/',
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'astr-binocular-8x21',
    dealerId: 'astroman',
    name: 'Binocular 8x21 Pocket',
    price: 89,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 8900,
    category: 'binocular',
    description: '8x21 pocket binoculars. Compact, lightweight — perfect for kids, travel, and casual stargazing.',
    image: 'https://astroman.ge/wp-content/uploads/2025/12/Document.jpg',
    externalUrl: 'https://astroman.ge/binocular-8x21/',
    specs: { magnification: '8x', aperture: '21mm' },
  },
  {
    id: 'astr-vintage-monocular',
    dealerId: 'astroman',
    name: 'Vintage Brass Monocular',
    price: 129,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 12900,
    category: 'binocular',
    description: 'Classic brass-finish monocular telescope. Beautiful collectible piece — also functional for nature use.',
    image: 'https://astroman.ge/wp-content/uploads/2025/01/ბექი-02.jpg',
    externalUrl: 'https://astroman.ge/vinrage-monocular/',
    specs: { type: 'Monocular' },
  },
  {
    id: 'astr-mini-microscope',
    dealerId: 'astroman',
    name: 'Hand Mini Microscope',
    price: 69,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 6900,
    category: 'accessory',
    description: 'Pocket microscope with built-in LED. Up to 60x magnification — explore the small worlds too.',
    image: 'https://astroman.ge/wp-content/uploads/2023/10/-მიკროსკოპი-jpg.webp',
    externalUrl: 'https://astroman.ge/mini-microscope/',
    specs: { magnification: '60x' },
  },
  {
    id: 'astr-cosmonaut-moon-lamp',
    dealerId: 'astroman',
    name: 'Cosmonaut Moon Lamp',
    price: 85,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 8500,
    category: 'accessory',
    description: 'Cosmonaut riding the Moon — lamp with cosmic glow. Doubles as a redeemable Stars reward.',
    image: 'https://astroman.ge/wp-content/uploads/2024/06/ბექი-01.jpg',
    externalUrl: 'https://astroman.ge/cosmonaut-moon-lamp/',
  },
  {
    id: 'astr-earth-moon-projector',
    dealerId: 'astroman',
    name: 'Earth/Moon Projector',
    price: 119,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 11900,
    category: 'accessory',
    description: 'Dual projector — switch between Earth view and Moon view. Casts a soft cosmic ambience on your ceiling.',
    image: 'https://astroman.ge/wp-content/uploads/2024/08/222122-02-scaled.jpg',
    externalUrl: 'https://astroman.ge/projector-earthmoon/',
  },
  {
    id: 'astr-3d-wood-planets',
    dealerId: 'astroman',
    name: '3D Wood Planets',
    price: 75,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 7500,
    category: 'accessory',
    description: 'Hand-crafted 3D wooden Solar System set — eight planets carved to scale. Display piece for any astronomer.',
    image: 'https://astroman.ge/wp-content/uploads/2023/10/-პლანეტები-jpg.webp',
    externalUrl: 'https://astroman.ge/3d-xis-planetebi/',
  },
  {
    id: 'astr-planet-desk-lamp',
    dealerId: 'astroman',
    name: 'Solar System Desk Lamp',
    price: 95,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 9500,
    category: 'accessory',
    description: 'Eight-planet desk lamp with glowing Sun core. Educational decor — kids learn the planets while it lights the room.',
    image: 'https://astroman.ge/wp-content/uploads/2023/09/-სანათები-jpg.webp',
    externalUrl: 'https://astroman.ge/planetebi-magidis-sanati/',
  },
  {
    id: 'astr-vr-glasses-shinecon',
    dealerId: 'astroman',
    name: 'VR Glasses Shinecon',
    price: 149,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 14900,
    category: 'accessory',
    description: 'VR headset for smartphones. Watch space documentaries and 360° NASA footage in immersive view.',
    image: 'https://astroman.ge/wp-content/uploads/2023/04/-რეალობის-სათვალე-jpg.webp',
    externalUrl: 'https://astroman.ge/vr-satvale/',
  },

  // Celestron US — additional products with verified CDN images
  {
    id: 'cel-astromaster-130eq',
    dealerId: 'celestron-us',
    name: 'Celestron AstroMaster 130EQ',
    price: 449.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 123286,
    category: 'telescope',
    description: '130mm Newtonian on equatorial mount. Bright deep-sky views with manual tracking. Classic first serious telescope.',
    image: 'https://www.celestron.com/cdn/shop/products/31045_AstroMaster_130EQ_1.jpg?v=1534171935&width=1200',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '130mm', focal: '650mm', mount: 'EQ-2 Equatorial' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'cel-powerseeker-127eq',
    dealerId: 'celestron-us',
    name: 'Celestron PowerSeeker 127EQ',
    price: 229.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 63006,
    category: 'telescope',
    description: '127mm reflector on equatorial mount. Great budget aperture for the Moon, planets, and brighter deep-sky.',
    image: 'https://www.celestron.com/cdn/shop/products/050234210492_PowerSeeker_127EQ_21049_1.jpg?v=1534172033&width=1200',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '127mm', focal: '1000mm', mount: 'EQ-2' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-firstscope',
    dealerId: 'celestron-us',
    name: 'Celestron FirstScope',
    price: 79.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 21906,
    category: 'telescope',
    description: '76mm tabletop Dobsonian. Tiny footprint, point-and-look simplicity. Honored by IAU as a great first scope.',
    image: 'https://www.celestron.com/cdn/shop/products/22025_NPF_FIRSTSCOPE_1.jpg?v=1534172013&width=1200',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '76mm', focal: '300mm', mount: 'Tabletop Dobsonian' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-omni-xlt-150',
    dealerId: 'celestron-us',
    name: 'Celestron Omni XLT 150',
    price: 999,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 273726,
    category: 'telescope',
    description: '150mm Newtonian on Omni CG-4 equatorial mount with StarBright XLT coatings. Serious mid-range scope.',
    image: 'https://www.celestron.com/cdn/shop/products/31057_omnixlt150_large_2.jpg?v=1534172018&width=1200',
    externalUrl: 'https://www.celestron.com/collections/telescopes',
    specs: { aperture: '150mm', focal: '750mm', mount: 'CG-4 Equatorial' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'cel-skyprodigy-130',
    dealerId: 'celestron-us',
    name: 'Celestron SkyProdigy 130',
    price: 899,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 246326,
    category: 'telescope',
    description: '130mm computerized Newtonian with StarSense auto-align — points itself with the press of a button.',
    image: 'https://www.celestron.com/cdn/shop/products/31153_SkyProdigy_130_Computerized_Telescope_1.jpg?v=1534172037&width=1200',
    externalUrl: 'https://www.celestron.com/search?q=skyprodigy',
    specs: { aperture: '130mm', focal: '650mm', mount: 'GoTo Alt-Az' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'cel-zoom-eyepiece',
    dealerId: 'celestron-us',
    name: 'Celestron 8-24mm Zoom Eyepiece',
    price: 79.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 21906,
    category: 'eyepiece',
    description: 'Variable 8–24mm zoom eyepiece. One-piece replacement for an entire eyepiece set — twist to change power.',
    image: 'https://www.celestron.com/cdn/shop/products/93230-zoom-eyepiece-8-24-mm_02.jpg?v=1603736935&width=1200',
    externalUrl: 'https://www.celestron.com/products/8-24mm-zoom-eyepiece-125in',
    specs: { focal: '8-24mm', barrel: '1.25"' },
  },
  {
    id: 'cel-omni-eyepiece-12',
    dealerId: 'celestron-us',
    name: 'Celestron Omni 12mm Plössl',
    price: 39.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 10946,
    category: 'eyepiece',
    description: '12mm Plössl eyepiece — sharp images, multi-coated optics. A reliable workhorse for any 1.25" telescope.',
    image: 'https://www.celestron.com/cdn/shop/products/93319-omni.jpg?v=1590984281&width=1200',
    externalUrl: 'https://www.celestron.com/collections/eyepieces',
    specs: { focal: '12mm', afov: '50°', barrel: '1.25"' },
  },
  {
    id: 'cel-skymaster-15x70',
    dealerId: 'celestron-us',
    name: 'Celestron SkyMaster 15x70',
    price: 89.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 24646,
    category: 'binocular',
    description: '15x70 astronomy binoculars — the favorite first deep-sky instrument. Great for Andromeda and clusters.',
    image: 'https://www.celestron.com/cdn/shop/files/71009_skymaster_15x70_1.jpg?v=1765921503&width=1200',
    externalUrl: 'https://www.celestron.com/collections/binoculars',
    specs: { magnification: '15x', aperture: '70mm', prism: 'BaK-4 Porro' },
  },
  {
    id: 'cel-nature-dx-8x42',
    dealerId: 'celestron-us',
    name: 'Celestron Nature DX 8x42',
    price: 159.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 43826,
    category: 'binocular',
    description: '8x42 roof-prism binoculars. Excellent for daytime nature use and casual stargazing — fully waterproof.',
    image: 'https://www.celestron.com/cdn/shop/products/71332_nature_dx_8x42_1-R.jpg?v=1654808560&width=1200',
    externalUrl: 'https://www.celestron.com/collections/binoculars',
    specs: { magnification: '8x', aperture: '42mm', prism: 'BaK-4 Roof' },
  },
  {
    id: 'cel-nexyz-adapter',
    dealerId: 'celestron-us',
    name: 'Celestron NexYZ Smartphone Adapter',
    price: 64.95,
    currency: 'USD',
    currencySymbol: '$',
    starsPrice: 17796,
    category: 'accessory',
    description: '3-axis universal phone mount. Precise X/Y/Z alignment to any eyepiece — capture the Moon and planets.',
    image: 'https://www.celestron.com/cdn/shop/products/81055_NexYZ_3-Axis_Universal_Smartphone_Adapter_01.jpg?v=1635196930&width=1200',
    externalUrl: 'https://www.celestron.com/products/nexyz-3-axis-universal-smartphone-adapter',
    specs: { type: 'Phone adapter', axes: '3' },
  },

  // Levenhuk EU — real catalog products with verified CDN images
  {
    id: 'lev-skyline-plus-90-az3',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PLUS 90 AZ3',
    price: 199,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 58904,
    category: 'telescope',
    description: '90mm refractor on AZ3 alt-az mount. Sharp planetary views with sturdy slow-motion controls.',
    image: 'https://levenhuk.com/upload/iblock/0c6/wofse0sryn2a6mrniuw3f49y1biuziqd/86208_levenhuk-telescope-new-skyline-plus-90x900-az3_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-new-skyline-plus-90-900-az3-telescope/',
    specs: { aperture: '90mm', focal: '900mm', mount: 'AZ3 Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-skyline-pro-127-mak',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PRO 127 MAK',
    price: 549,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 162504,
    category: 'telescope',
    description: '127mm Maksutov-Cassegrain — sharp, high-contrast planetary views in a compact tube. Premium glass.',
    image: 'https://levenhuk.com/upload/iblock/308/j5oes9l0a5m7zl02agrq3ol6yd236dvv/levenhuk-skyline-pro-127-mac_ZZrngEd.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-pro-127-mak-telescope/',
    badge: 'Premium',
    specs: { aperture: '127mm', focal: '1500mm', mount: 'EQ' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'lev-strike-90-plus',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Strike 90 PLUS',
    price: 159,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 47064,
    category: 'telescope',
    description: '90mm refractor full kit — eyepieces, Barlow, Moon filter, smartphone adapter, and book all included.',
    image: 'https://levenhuk.com/upload/iblock/0ff/t6wdsojzr6c6q3s3y5x5v1eni5e3w3w0/levenhuk-strike-90-plus_UJRseLF.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-strike-90-plus-telescope/',
    specs: { aperture: '90mm', focal: '600mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-blitz-60-base',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Blitz 60 BASE',
    price: 69,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 20424,
    category: 'telescope',
    description: '60mm refractor on simple alt-az mount. Step up from a 50mm — bigger, brighter views of Moon and planets.',
    image: 'https://levenhuk.com/upload/iblock/e4a/78q13v6ndy0tr3wc8cz2mztz4gunk8nj/77099_levenhuk-blitz-60-base-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-blitz-60-base-telescope/',
    specs: { aperture: '60mm', focal: '700mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-blitz-70-plus',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Blitz 70 PLUS',
    price: 99,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 29304,
    category: 'telescope',
    description: '70mm refractor full kit. Everything you need for a first night out — eyepieces, Barlow, smartphone adapter.',
    image: 'https://levenhuk.com/upload/iblock/631/bpsxbr70qsdmi1v2oa53yty3zqa4jr1d/77108_levenhuk-blitz-70-plus-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-blitz-70-plus-telescope/',
    specs: { aperture: '70mm', focal: '700mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-blitz-76-plus',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Blitz 76 PLUS',
    price: 159,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 47064,
    category: 'telescope',
    description: '76mm Newtonian reflector kit. Wide aperture for nebulae and brighter galaxies — eyepieces included.',
    image: 'https://levenhuk.com/upload/iblock/dc1/64akf3oov8labkyiwpjekaks2gk03qd5/77104_levenhuk-blitz-76-plus-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-blitz-76-plus-telescope/',
    specs: { aperture: '76mm', focal: '700mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-skyline-base-100s',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline BASE 100S',
    price: 219,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 64824,
    category: 'telescope',
    description: '100mm Newtonian on alt-az mount. Solid step-up scope — much more aperture than the 70 and 80 series.',
    image: 'https://levenhuk.com/upload/iblock/4f3/o7bf7uc1ln5ghvh14x1ffsabzlilvusf/levenhuk-telescope-skyline-base-100s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-base-100s-telescope/',
    specs: { aperture: '100mm', focal: '500mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-skyline-base-mak80',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline BASE MAK 80',
    price: 269,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 79624,
    category: 'telescope',
    description: '80mm Maksutov-Cassegrain. Compact, sharp planetary scope — fits in a backpack and resolves Saturn rings.',
    image: 'https://levenhuk.com/upload/iblock/c7d/1gt3ot4tmyadnp0obtwon62sw022fvhn/86253_levenhuk-new-skyline-base-mak-80-850-az-m-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-new-skyline-base-mak-80-850-az-m-telescope-/',
    specs: { aperture: '80mm', focal: '850mm', mount: 'AZ-M' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-skyline-pro-90-mak',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PRO 90 MAK',
    price: 379,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 112184,
    category: 'telescope',
    description: '90mm Maksutov-Cassegrain. Compact, sharp planetary scope with premium glass and long focal length.',
    image: 'https://levenhuk.com/upload/iblock/042/5w4dzu4dql5z5bhu7l28d0rynag476l2/levenhuk_skyline_pro_90mak_PRY8V2W.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-pro-90-mak-telescope/',
    specs: { aperture: '90mm', focal: '1250mm', mount: 'EQ' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'lev-skyline-pro-105-mak',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PRO 105 MAK',
    price: 459,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 135864,
    category: 'telescope',
    description: '105mm Maksutov-Cassegrain. Bigger aperture than the 90 MAK — sharper double stars and lunar detail.',
    image: 'https://levenhuk.com/upload/iblock/c77/8w64xsuns4i7ir4xgt3dhw1ukhby8sz4/levenhuk_skyline_pro_105mac_zoTpt7N.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-pro-105-mak-telescope/',
    specs: { aperture: '105mm', focal: '1300mm', mount: 'EQ' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'lev-skyline-base-120s',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline BASE 120S',
    price: 219,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 64824,
    category: 'telescope',
    description: '120mm reflector — large aperture at a fair price. Resolves brighter galaxies and faint nebulae.',
    image: 'https://levenhuk.com/upload/iblock/8fe/tf8i3yg65u1e2gr0utv2vpaj1bylia64/levenhuk-telescope-skyline-base-120s_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-skyline-base-120s-telescope/',
    specs: { aperture: '120mm', focal: '600mm', mount: 'Manual Alt-Az' },
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-skyline-plus-150-dob',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Skyline PLUS 6" Dobsonian',
    price: 499,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 147704,
    category: 'telescope',
    description: '150mm Dobsonian — serious aperture for deep-sky on a stable, intuitive base. Galaxies and nebulae come alive.',
    image: 'https://levenhuk.com/upload/iblock/294/fy1glo8ve2hm7i5tjhz7t53skil0wuge/86283_levenhuk-new-skyline-plus-6-telescope_00.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-new-skyline-plus-6-150-1200-dobsonian-telescope/',
    badge: 'Best Aperture',
    specs: { aperture: '150mm', focal: '1200mm', mount: 'Dobsonian' },
    skillLevel: 'advanced' as const,
  },
  {
    id: 'lev-strike-50-ng',
    dealerId: 'levenhuk-eu',
    name: 'Levenhuk Strike 50 NG',
    price: 49,
    currency: 'EUR',
    currencySymbol: '€',
    starsPrice: 14504,
    category: 'telescope',
    description: '50mm refractor entry kit. Lightweight, simple — a great first telescope for kids learning the night sky.',
    image: 'https://levenhuk.com/upload/iblock/9d3/ljl2qr20od3mt58w3uyjj5j71w6wulqe/levenhuk_strike_50_Te4jz3m.jpg',
    externalUrl: 'https://levenhuk.com/catalogue/telescopes/levenhuk-strike-50-ng-telescope/',
    specs: { aperture: '50mm', focal: '600mm', mount: 'Manual Alt-Az' },
    beginner: true,
    skillLevel: 'beginner' as const,
  },

  // ─── Star Shop (Stars-only inventory) ──────────────────────────────────────
  // §5A: in-app shop tier where users spend the Stars SPL token — no SOL / fiat.
  // priceStars is the source of truth; price is set to 0 and not displayed.
  {
    id: 'star-shop-patch',
    dealerId: 'astroman',
    kind: 'stars-only',
    name: 'Astroman Embroidered Patch',
    price: 0,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 1000,
    category: 'accessory',
    description: 'Iron-on cloth patch — the Astroman logo. Pickup at the Tbilisi store or shipped to anywhere in Georgia.',
    image: 'https://astroman.ge/wp-content/uploads/2024/08/Telescope.jpg',
    externalUrl: 'https://astroman.ge',
  },
  {
    id: 'star-shop-redlight',
    dealerId: 'astroman',
    kind: 'stars-only',
    name: 'Red-Light Astronomer Flashlight',
    price: 0,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 3000,
    category: 'accessory',
    description: 'Dim red-LED flashlight that preserves dark adaptation. Essential for star charts under the night sky.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge',
  },
  {
    id: 'star-shop-laser',
    dealerId: 'astroman',
    kind: 'stars-only',
    name: 'Green Astronomy Laser Pointer',
    price: 0,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 5000,
    category: 'accessory',
    description: 'Green-beam laser pointer for sky tours — point out planets and constellations to anyone next to you.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge',
  },
  {
    id: 'star-shop-planisphere',
    dealerId: 'astroman',
    kind: 'stars-only',
    name: 'Planisphere (40°N rotating star chart)',
    price: 0,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 8000,
    category: 'accessory',
    description: 'Rotating star map calibrated for 40°N — find what is visible right now from Tbilisi or anywhere on the same latitude.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/-%E1%83%A1%E1%83%90%E1%83%9C%E1%83%90%E1%83%97%E1%83%98-3D--jpg.webp',
    externalUrl: 'https://astroman.ge',
  },
  {
    id: 'star-shop-eyepiece-kit',
    dealerId: 'astroman',
    kind: 'stars-only',
    name: '4-Piece Plossl Eyepiece Kit',
    price: 0,
    currency: 'GEL',
    currencySymbol: '₾',
    starsPrice: 15000,
    category: 'eyepiece',
    description: 'Set of four 1.25" Plossl eyepieces (32mm / 17mm / 10mm / 6mm). Covers wide-field to high-power planetary work.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/%E1%83%90%E1%83%93%E1%83%90%E1%83%9E%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98.jpg',
    externalUrl: 'https://astroman.ge',
  },

  // ── Celestron (US) — catalogue top-up ──
  {
    id: 'cel-nexstar-4se', dealerId: 'celestron-us', name: 'Celestron NexStar 4SE',
    price: 649, currency: 'USD', currencySymbol: '$', starsPrice: 64900, category: 'telescope',
    description: '102mm Maksutov-Cassegrain on a fully automated GoTo mount. 40,000-object database, single-arm fork for grab-and-go nights.',
    image: 'https://www.celestron.com/cdn/shop/products/050234110495_NexStar_4SE_11049_1.jpg',
    externalUrl: 'https://www.celestron.com/products/nexstar-4se-computerized-telescope',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'cel-nexstar-5se', dealerId: 'celestron-us', name: 'Celestron NexStar 5SE',
    price: 899, currency: 'USD', currencySymbol: '$', starsPrice: 89900, category: 'telescope',
    description: '125mm Schmidt-Cassegrain with computerized GoTo. Sharp lunar, planetary and brighter deep-sky views in a portable package.',
    image: 'https://www.celestron.com/cdn/shop/products/050234110365_NexStar_5SE_11036_1.jpg',
    externalUrl: 'https://www.celestron.com/products/nexstar-5se-computerized-telescope',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'cel-nexstar-130slt', dealerId: 'celestron-us', name: 'Celestron NexStar 130SLT',
    price: 699.95, currency: 'USD', currencySymbol: '$', starsPrice: 69995, category: 'telescope',
    description: '130mm Newtonian reflector on a motorized GoTo mount. Generous aperture for nebulae and clusters at an approachable price.',
    image: 'https://www.celestron.com/cdn/shop/products/050234311458_NexStar_130SLT_31145_1.jpg',
    externalUrl: 'https://www.celestron.com/products/nexstar-130slt-computerized-telescope',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'cel-nexstar-evolution-8', dealerId: 'celestron-us', name: 'Celestron NexStar Evolution 8',
    price: 2399, currency: 'USD', currencySymbol: '$', starsPrice: 239900, category: 'telescope',
    description: '8-inch Schmidt-Cassegrain with built-in WiFi and lithium battery. Control the whole night from your phone, no cables.',
    image: 'https://www.celestron.com/cdn/shop/products/12091_NexStar_Evolution_8_1_1794d472-3dd3-45f7-9dc8-e746ce0bcce5.jpg',
    externalUrl: 'https://www.celestron.com/products/nexstar-evolution-8-telescope',
    skillLevel: 'advanced' as const,
  },
  {
    id: 'cel-nexstar-evolution-8-hd', dealerId: 'celestron-us', name: 'Celestron NexStar Evolution 8 HD + StarSense',
    price: 3199, currency: 'USD', currencySymbol: '$', starsPrice: 319900, category: 'telescope',
    description: '8" EdgeHD optics, WiFi and StarSense auto-alignment. Coma-free flat field built for visual work and astrophotography.',
    image: 'https://www.celestron.com/cdn/shop/products/12096_Nexstar_Evolution_HD_1.jpg',
    externalUrl: 'https://www.celestron.com/products/nexstar-evolution-8-hd-telescope-with-starsense',
    skillLevel: 'advanced' as const,
  },
  {
    id: 'cel-starsense-8-dob', dealerId: 'celestron-us', name: 'StarSense Explorer 8" Dobsonian',
    price: 879, currency: 'USD', currencySymbol: '$', starsPrice: 87900, category: 'telescope',
    description: '8-inch Dobsonian with StarSense smartphone star-finding. Point your phone at the sky and it walks you to the target.',
    image: 'https://www.celestron.com/cdn/shop/files/22470_StarSense_Explorer_8in_Dobsonian_00.jpg',
    externalUrl: 'https://www.celestron.com/products/starsense-explorer-8-smartphone-app-enabled-dobsonian-telescope',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'cel-starsense-10-dob', dealerId: 'celestron-us', name: 'StarSense Explorer 10" Dobsonian',
    price: 1199, currency: 'USD', currencySymbol: '$', starsPrice: 119900, category: 'telescope',
    description: '10-inch light bucket with smartphone-guided navigation. Huge aperture for galaxies and faint nebulae from darker skies.',
    image: 'https://www.celestron.com/cdn/shop/files/22471_StarSense_Explorer_10in_Dobsonian_00.jpg',
    externalUrl: 'https://www.celestron.com/products/starsense-explorer-10-smartphone-app-enabled-dobsonian-telescope',
    skillLevel: 'advanced' as const,
  },
  {
    id: 'cel-astromaster-70az', dealerId: 'celestron-us', name: 'Celestron AstroMaster 70AZ',
    price: 199.95, currency: 'USD', currencySymbol: '$', starsPrice: 19995, category: 'telescope',
    description: '70mm refractor on an alt-azimuth mount. Crisp Moon and planet views straight out of the box — a classic first scope.',
    image: 'https://www.celestron.com/cdn/shop/products/21061_AstroMaster_70AZ_1.jpg',
    externalUrl: 'https://www.celestron.com/products/astromaster-70az-telescope',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-astromaster-102az', dealerId: 'celestron-us', name: 'Celestron AstroMaster 102AZ',
    price: 359.95, currency: 'USD', currencySymbol: '$', starsPrice: 35995, category: 'telescope',
    description: '102mm refractor with StarPointer finder on an alt-az mount. Brighter images and wide fields for lunar and planetary nights.',
    image: 'https://www.celestron.com/cdn/shop/products/22065_Astromaster_102AZ_StarPointer_01.jpg',
    externalUrl: 'https://www.celestron.com/products/astromaster-102az-telescope',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-powerseeker-80eq', dealerId: 'celestron-us', name: 'Celestron PowerSeeker 80EQ',
    price: 209.95, currency: 'USD', currencySymbol: '$', starsPrice: 20995, category: 'telescope',
    description: '80mm refractor on a German equatorial mount with slow-motion controls. A budget-friendly route into tracked observing.',
    image: 'https://www.celestron.com/cdn/shop/products/050234210485_PowerSeeker_80EQ_21048_1.jpg',
    externalUrl: 'https://www.celestron.com/products/powerseeker-80eq-telescope',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-travelscope-70dx', dealerId: 'celestron-us', name: 'Celestron Travel Scope 70 DX',
    price: 129.95, currency: 'USD', currencySymbol: '$', starsPrice: 12995, category: 'telescope',
    description: '70mm portable refractor with backpack, tripod and smartphone adapter. Built for travel, terrestrial and casual sky viewing.',
    image: 'https://www.celestron.com/cdn/shop/products/22035_Travel_Scope_70_DX_01_89595b4c-83fd-4cd8-a869-138e307af892.jpg',
    externalUrl: 'https://www.celestron.com/products/travel-scope-70-dx-portable-telescope-with-smartphone-adapter',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-starsense-lt80', dealerId: 'celestron-us', name: 'StarSense Explorer LT 80AZ',
    price: 249.95, currency: 'USD', currencySymbol: '$', starsPrice: 24995, category: 'telescope',
    description: '80mm refractor with StarSense phone-guided star finding. The app draws a live bullseye to the object you want to see.',
    image: 'https://www.celestron.com/cdn/shop/products/22451_StarSense_Explorer_LT_80_01.jpg',
    externalUrl: 'https://www.celestron.com/products/starsense-explorer-lt-80az',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-moon-mission-100', dealerId: 'celestron-us', name: 'Celestron Moon Mission 100mm Dobsonian',
    price: 179.95, currency: 'USD', currencySymbol: '$', starsPrice: 17995, category: 'telescope',
    description: '100mm tabletop Dobsonian tuned for the Moon. Simple push-to aiming and bright, contrasty lunar detail for all ages.',
    image: 'https://www.celestron.com/cdn/shop/files/22018_Moon_Mission_Tabletop_Dob_100_01.jpg',
    externalUrl: 'https://www.celestron.com/products/moon-mission-100mm-tabletop-dobsonian',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-firstscope-moon', dealerId: 'celestron-us', name: 'Celestron FirstScope Moon (Signature Series)',
    price: 74.95, currency: 'USD', currencySymbol: '$', starsPrice: 7495, category: 'telescope',
    description: '76mm tabletop Dobsonian with a lunar-map livery by Robert Reeves. A genuine grab-and-go starter for kids and beginners.',
    image: 'https://www.celestron.com/cdn/shop/products/22016_FirstScope_Signature_Series_Moon_01_9689cfe0-1019-4f39-b2e6-75ede11d4013.jpg',
    externalUrl: 'https://www.celestron.com/products/firstscope-signature-series-moon-by-robert-reeves-telescope',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-npf-firstscope', dealerId: 'celestron-us', name: 'Celestron National Park Foundation FirstScope',
    price: 79.95, currency: 'USD', currencySymbol: '$', starsPrice: 7995, category: 'telescope',
    description: '76mm tabletop reflector in National Park Foundation trim. Tool-free setup and surprisingly capable Moon and planet views.',
    image: 'https://www.celestron.com/cdn/shop/products/22025_NPF_FIRSTSCOPE_1.jpg',
    externalUrl: 'https://www.celestron.com/products/npf-firstscope-telescope',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'cel-trailseeker-ed-8x42', dealerId: 'celestron-us', name: 'Celestron TrailSeeker ED 8x42',
    price: 399.95, currency: 'USD', currencySymbol: '$', starsPrice: 39995, category: 'binocular',
    description: 'ED-glass roof-prism binoculars, 8x42. Phase-coated, fully waterproof — sharp wide fields for stargazing and daytime use.',
    image: 'https://www.celestron.com/cdn/shop/products/71405_8x42_TrailSeekerED_01.jpg',
    externalUrl: 'https://www.celestron.com/products/trailseeker-ed-8x42mm-roof-binoculars',
  },
  {
    id: 'cel-cometron-7x50', dealerId: 'celestron-us', name: 'Celestron Cometron 7x50',
    price: 47.95, currency: 'USD', currencySymbol: '$', starsPrice: 4795, category: 'binocular',
    description: '7x50 Porro binoculars with a wide true field and big 50mm objectives. An ideal, affordable first instrument for the sky.',
    image: 'https://www.celestron.com/cdn/shop/products/71198_cometron_binos_7x50_1.jpg',
    externalUrl: 'https://www.celestron.com/products/cometron-7x50mm-porro-binoculars',
  },
  {
    id: 'cel-skymaster-20x80', dealerId: 'celestron-us', name: 'Celestron SkyMaster 20x80',
    price: 209.95, currency: 'USD', currencySymbol: '$', starsPrice: 20995, category: 'binocular',
    description: '20x80 giant astronomy binoculars. Large objectives pull in star clusters and the Milky Way; tripod-ready for steady views.',
    image: 'https://www.celestron.com/cdn/shop/products/71018_skymaster_20x80_front.jpg',
    externalUrl: 'https://www.celestron.com/products/skymaster-20x80mm-porro-binoculars',
  },
  {
    id: 'cel-skymaster-25x100', dealerId: 'celestron-us', name: 'Celestron SkyMaster 25x100',
    price: 519.95, currency: 'USD', currencySymbol: '$', starsPrice: 51995, category: 'binocular',
    description: '25x100 large-aperture binoculars for serious deep-sky scanning. Tripod mounting essential; rewards with rich star fields.',
    image: 'https://www.celestron.com/cdn/shop/products/71017_skymaster_25x100_front.jpg',
    externalUrl: 'https://www.celestron.com/products/skymaster-25x100mm-porro-binoculars',
  },
  {
    id: 'cel-nature-dx-12x56', dealerId: 'celestron-us', name: 'Celestron Nature DX 12x56',
    price: 289.95, currency: 'USD', currencySymbol: '$', starsPrice: 28995, category: 'binocular',
    description: '12x56 phase-coated roof binoculars. Higher power with bright 56mm optics — strong for both wildlife and casual astronomy.',
    image: 'https://www.celestron.com/cdn/shop/products/71336_nature_dx_12x56_1-R.jpg',
    externalUrl: 'https://www.celestron.com/products/nature-dx-12x56mm-roof-binoculars',
  },
  {
    id: 'cel-outland-x-8x42', dealerId: 'celestron-us', name: 'Celestron Outland X 8x42',
    price: 109.95, currency: 'USD', currencySymbol: '$', starsPrice: 10995, category: 'binocular',
    description: '8x42 waterproof, fog-proof roof binoculars with twist-up eyecups. A rugged, value all-rounder for the field and the sky.',
    image: 'https://www.celestron.com/cdn/shop/products/71346_outlandx_front.jpg',
    externalUrl: 'https://www.celestron.com/products/outland-x-8x42mm-roof-binoculars',
  },

  // ── Bresser (DE) — full catalogue ──
  {
    id: 'bres-lyra-70-900', dealerId: 'bresser-eu', name: 'Bresser Lyra 70/900 EQ3',
    price: 149, currency: 'EUR', currencySymbol: '€', starsPrice: 14900, category: 'telescope',
    description: '70mm refractor, 900mm focal length on an EQ3 mount. Ships with a smartphone adapter and solar filter for day and night.',
    image: 'https://www.bresser.com/media/e6/bc/5b/1644259327/4670900_M1_2019.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-lyra-70-900-eq3-refractor-telescope-with-smartphone-adapter-solar-filter-4670909',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'bres-arcturus-60-700', dealerId: 'bresser-eu', name: 'Bresser Arcturus 60/700 AZ',
    price: 112, currency: 'EUR', currencySymbol: '€', starsPrice: 11200, category: 'telescope',
    description: '60mm alt-azimuth refractor with a hard carry case. Light, simple and quick to set up — a tidy starter for Moon and planets.',
    image: 'https://www.bresser.com/media/af/42/0d/1664445953/4511600_M_1.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-arcturus-60-700-az-refractor-telescope-with-hard-top-case-4511600',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'bres-sirius-70-900', dealerId: 'bresser-eu', name: 'Bresser Sirius 70/900 AZ',
    price: 146, currency: 'EUR', currencySymbol: '€', starsPrice: 14600, category: 'telescope',
    description: '70/900 alt-az refractor with smartphone camera adapter. Long focal length gives steady, high-contrast lunar and planetary views.',
    image: 'https://www.bresser.com/media/91/fd/b7/1772098134/4512001_M_V2019.webp',
    externalUrl: 'https://www.bresser.com/p/bresser-sirius-70-900-az-refractor-telescope-with-smartphone-camera-adapter-4512001',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'bres-messier-ar90-900', dealerId: 'bresser-eu', name: 'Bresser Messier AR-90/900 EXOS1/EQ4',
    price: 429, currency: 'EUR', currencySymbol: '€', starsPrice: 42900, category: 'telescope',
    description: '90mm achromatic refractor on a sturdy EXOS-1/EQ4 equatorial mount. Serious aperture and tracking for planetary detail.',
    image: 'https://www.bresser.com/media/4a/63/b7/1644261197/4790907_M1_2020_Sonnenfilter.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-messier-ar-90-900-exos1-eq4-telescope-4790907',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-quasar-80-900', dealerId: 'bresser-eu', name: 'Bresser Quasar 80/900 EQ',
    price: 289, currency: 'EUR', currencySymbol: '€', starsPrice: 28900, category: 'telescope',
    description: '80mm refractor on an equatorial mount with smartphone camera adapter. A capable step-up scope for tracked observing.',
    image: 'https://www.bresser.com/media/9b/7f/2b/1644316026/4780909_M1_2019.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-quasar-80-900-eq-refractor-telescope-with-smartphone-camera-adapter-4780909',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-classic-70-350', dealerId: 'bresser-eu', name: 'Bresser Classic 70/350',
    price: 125, currency: 'EUR', currencySymbol: '€', starsPrice: 12500, category: 'telescope',
    description: '70mm short-tube refractor set, 350mm focal length. Wide, bright fields and full portability for rich-field sky sweeps.',
    image: 'https://www.bresser.com/media/c6/e2/e1/1644331600/4670350_M_2_0117.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-classic-70-350-refractor-telescope-set-4670350',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'bres-polaris-i-102-460', dealerId: 'bresser-eu', name: 'Bresser Polaris-I 102/460 EQ3',
    price: 249, currency: 'EUR', currencySymbol: '€', starsPrice: 24900, category: 'telescope',
    description: '102mm fast refractor on an EQ3 mount with smartphone adapter and solar filter. Wide-field astronomy plus safe solar viewing.',
    image: 'https://www.bresser.com/media/7f/6e/2d/1772097801/4602460_M_1_v0219.webp',
    externalUrl: 'https://www.bresser.com/p/bresser-polaris-i-102-460-eq3-refractor-telescope-with-smartphone-adapter-solar-filter-4602460',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-polaris-ii-102-600', dealerId: 'bresser-eu', name: 'Bresser Polaris-II 102/600 EQ3',
    price: 389, currency: 'EUR', currencySymbol: '€', starsPrice: 38900, category: 'telescope',
    description: '102/600 refractor on an EQ3 equatorial mount. Longer focal length than the Polaris-I for tighter planetary and lunar work.',
    image: 'https://www.bresser.com/media/c6/90/3c/1657539135/4602600_M2_2022.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-polaris-ii-102-600-eq3-refractor-telescope-with-smartphone-adapter-solar-filter-4602600',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-messier-mcx127', dealerId: 'bresser-eu', name: 'Bresser Messier MCX-127 GoTo',
    price: 949, currency: 'EUR', currencySymbol: '€', starsPrice: 94900, category: 'telescope',
    description: '127mm Maksutov-Cassegrain with GoTo on an EQ/AZ mount. Compact, long focal length optics ideal for planets and the Moon.',
    image: 'https://www.bresser.com/media/85/bb/13/1660211715/4701127_M_1_v0422_mit-Sonenfilter.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-messier-mcx-127-goto-telescope-eq-az-4701127',
    skillLevel: 'advanced' as const,
  },
  {
    id: 'bres-nano-ar80-640', dealerId: 'bresser-eu', name: 'Bresser NANO AR-80/640 AZ',
    price: 209, currency: 'EUR', currencySymbol: '€', starsPrice: 20900, category: 'telescope',
    description: '80mm refractor on the lightweight NANO alt-az mount. Travel-friendly with sharp, contrasty views of Moon and bright planets.',
    image: 'https://www.bresser.com/media/1e/61/5d/1772098268/4580640_M_2_v0921.webp',
    externalUrl: 'https://www.bresser.com/p/bresser-nano-ar-80-640-az-telescope-4580640',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-firstlight-ar102-1000', dealerId: 'bresser-eu', name: 'Bresser First Light AR-102/1000',
    price: 399, currency: 'EUR', currencySymbol: '€', starsPrice: 39900, category: 'telescope',
    description: '102mm achromat, 1000mm focal length. The long tube delivers crisp, high-power planetary and lunar detail for keen observers.',
    image: 'https://www.bresser.com/media/33/07/1e/1678098138/0115660_M1_BRESSER_v032023.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-first-light-ar-102-1000-0115660',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-natgeo-60-700', dealerId: 'bresser-eu', name: 'National Geographic 60/700 AZ',
    price: 79, currency: 'EUR', currencySymbol: '€', starsPrice: 7900, category: 'telescope',
    description: '60mm alt-az refractor from the Bresser-built National Geographic line. An easy, affordable entry into night-sky observing.',
    image: 'https://www.bresser.com/media/1a/95/b3/1761309893/9011100_M_01_v1025.jpg',
    externalUrl: 'https://www.bresser.com/p/national-geographic-60-700-refracting-telescope-az-9011100',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'bres-pollux-ii-150', dealerId: 'bresser-eu', name: 'Bresser Pollux-II 150/1400 EQ3',
    price: 369, currency: 'EUR', currencySymbol: '€', starsPrice: 36900, category: 'telescope',
    description: '150mm reflector, 1400mm focal length on an EQ3 mount. Big aperture and long focus for detailed planetary and lunar views.',
    image: 'https://www.bresser.com/media/71/3e/61/1772097582/4690900_M_01_v0823.webp',
    externalUrl: 'https://www.bresser.com/p/bresser-pollux-ii-150-1400-eq3-reflector-telescope-with-smartphone-adapter-solar-filter-4690900',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-pluto-114-500', dealerId: 'bresser-eu', name: 'Bresser Pluto 114/500 EQ3',
    price: 229, currency: 'EUR', currencySymbol: '€', starsPrice: 22900, category: 'telescope',
    description: '114mm fast Newtonian on an EQ3 mount with smartphone adapter and solar filter. Wide-field deep-sky on a modest budget.',
    image: 'https://www.bresser.com/media/4c/36/5f/1772098041/4614500_M1_2019.webp',
    externalUrl: 'https://www.bresser.com/p/bresser-pluto-114-500-eq3-reflector-telescope-with-smartphone-adapter-solar-filter-4614500',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'bres-natgeo-114-900', dealerId: 'bresser-eu', name: 'National Geographic 114/900 AZ',
    price: 159.90, currency: 'EUR', currencySymbol: '€', starsPrice: 15990, category: 'telescope',
    description: '114mm Newtonian reflector on an alt-az mount. Solid aperture for clusters and nebulae from the National Geographic range.',
    image: 'https://www.bresser.com/media/bc/8d/1c/1763650950/9011200_M_011_2_v1125.jpg',
    externalUrl: 'https://www.bresser.com/p/national-geographic-114-900-reflector-telescope-az-9011200',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'bres-venus-76-700', dealerId: 'bresser-eu', name: 'Bresser Venus 76/700 AZ',
    price: 125, currency: 'EUR', currencySymbol: '€', starsPrice: 12500, category: 'telescope',
    description: '76mm reflector, 700mm focal length on an alt-az mount with smartphone adapter and solar filter. A friendly all-rounder.',
    image: 'https://www.bresser.com/media/68/79/a5/1772098542/4541009_M_2019.webp',
    externalUrl: 'https://www.bresser.com/p/bresser-venus-76-700-az-reflector-telescope-with-smartphone-adapter-solar-filter-4541009',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'bres-nano-nt114-500', dealerId: 'bresser-eu', name: 'Bresser NANO NT-114/500',
    price: 219, currency: 'EUR', currencySymbol: '€', starsPrice: 21900, category: 'telescope',
    description: '114mm fast Newtonian on the portable NANO alt-az mount. Quick-deploy aperture for bright deep-sky and wide star fields.',
    image: 'https://www.bresser.com/media/aa/2e/56/1644266801/4514500_M_2_v0921.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-nano-nt-114-500-telescope-4514500',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-messier-6-planetary-dob', dealerId: 'bresser-eu', name: 'Bresser Messier 6" Planetary Dobson',
    price: 339, currency: 'EUR', currencySymbol: '€', starsPrice: 33900, category: 'telescope',
    description: '150mm Dobsonian optimised for planetary detail. Simple point-and-look operation with the contrast a long-focus Newtonian gives.',
    image: 'https://www.bresser.com/media/30/8c/4a/1772098361/4716416_M_1.webp',
    externalUrl: 'https://www.bresser.com/p/bresser-messier-6-planetary-dobson-telescope-4716416',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-spica-130-650', dealerId: 'bresser-eu', name: 'Bresser Spica-I 130/650 EQ3',
    price: 329, currency: 'EUR', currencySymbol: '€', starsPrice: 32900, category: 'telescope',
    description: '130mm fast Newtonian on an EQ3 mount with smartphone adapter and solar filter. Generous light grasp for the price.',
    image: 'https://www.bresser.com/media/73/6c/2c/1644259382/4690919_M1_2019.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-spica-i-130-650-eq3-reflector-telescope-with-smartphone-adapter-solar-filter-4690919',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-messier-5-dob', dealerId: 'bresser-eu', name: 'Bresser Messier 5" Dobson',
    price: 239, currency: 'EUR', currencySymbol: '€', starsPrice: 23900, category: 'telescope',
    description: '127mm Dobsonian — a compact, no-fuss light bucket. Set it on the ground or a table and start sweeping the Moon and clusters.',
    image: 'https://www.bresser.com/media/b8/63/a3/1644243024/4716413_M_1_v0517_mit_Sonnenfilter.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-messier-5-dobson-4716413',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'bres-messier-6-dob', dealerId: 'bresser-eu', name: 'Bresser Messier 6" Dobson',
    price: 369, currency: 'EUR', currencySymbol: '€', starsPrice: 36900, category: 'telescope',
    description: '150mm Dobsonian with the classic grab-and-go simplicity. A great first serious aperture for galaxies, nebulae and clusters.',
    image: 'https://www.bresser.com/media/ee/8a/83/1772097702/4716415_M_1_v0617_mit_Sonnenfilter.webp',
    externalUrl: 'https://www.bresser.com/p/bresser-messier-6-dobson-4716415',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-natgeo-76-700', dealerId: 'bresser-eu', name: 'National Geographic 76/700 EQ',
    price: 189.90, currency: 'EUR', currencySymbol: '€', starsPrice: 18990, category: 'telescope',
    description: '76mm Newtonian reflector on an equatorial mount. Tracks the sky by hand for steadier Moon and planet sessions.',
    image: 'https://www.bresser.com/media/3f/78/cf/1734073561/9011000_M_01_v1224.jpg',
    externalUrl: 'https://www.bresser.com/p/national-geographic-76-700-reflector-telescope-eq-9011000',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'bres-pollux-i-150-750', dealerId: 'bresser-eu', name: 'Bresser Pollux-I 150/750 EQ3',
    price: 389, currency: 'EUR', currencySymbol: '€', starsPrice: 38900, category: 'telescope',
    description: '150mm fast Newtonian, 750mm focal length on an EQ3 mount. Wide-field deep-sky reach with bright, expansive star fields.',
    image: 'https://www.bresser.com/media/be/ea/82/1644259292/4650750_M_1_v0219.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-pollux-i-150-750-eq3-reflector-telescope-with-smartphone-adapter-solar-filter-4650750',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'bres-messier-12-dob', dealerId: 'bresser-eu', name: 'Bresser Messier 12" Dobson',
    price: 998, currency: 'EUR', currencySymbol: '€', starsPrice: 99800, category: 'telescope',
    description: '305mm Dobsonian — a true light bucket for faint galaxies and nebulae. Big aperture, simple aiming, dark-sky performance.',
    image: 'https://www.bresser.com/media/80/64/28/1706637884/4716430_M_01_v0923.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-messier-12-dobson-telescope-4716430',
    skillLevel: 'advanced' as const,
  },
  {
    id: 'bres-messier-8-dob', dealerId: 'bresser-eu', name: 'Bresser Messier 8" Dobson',
    price: 575, currency: 'EUR', currencySymbol: '€', starsPrice: 57500, category: 'telescope',
    description: '203mm Dobsonian, the sweet spot of aperture and portability. Resolves globular clusters and shows real galaxy structure.',
    image: 'https://www.bresser.com/media/12/fa/f9/1644260325/4716420_M_1_v2020.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-messier-8-dobsonian-4716420',
    skillLevel: 'advanced' as const,
  },
  {
    id: 'bres-natgeo-8-24x50', dealerId: 'bresser-eu', name: 'National Geographic 8-24x50 Zoom',
    price: 39.99, currency: 'EUR', currencySymbol: '€', starsPrice: 3999, category: 'binocular',
    description: '8-24x zoom binoculars with 50mm objectives. Dial up the magnification for the Moon, then zoom out for wide star fields.',
    image: 'https://www.bresser.com/media/fa/52/42/1761041743/9064000_M_1_v1025_.jpg',
    externalUrl: 'https://www.bresser.com/p/national-geographic-8-24x50-zoom-binoculars-9064000',
  },
  {
    id: 'bres-natgeo-10x42-algonquin', dealerId: 'bresser-eu', name: 'National Geographic 10x42 Algonquin',
    price: 79, currency: 'EUR', currencySymbol: '€', starsPrice: 7900, category: 'binocular',
    description: '10x42 roof-prism binoculars for the outdoors and the sky. Compact, bright and comfortable for handheld stargazing.',
    image: 'https://www.bresser.com/media/85/5e/e3/1761054633/9676207_M_01_v1025_.jpg',
    externalUrl: 'https://www.bresser.com/p/national-geographic-binoculars-10x42-algonquin-9676207',
  },
  {
    id: 'bres-spezial-astro-25x70', dealerId: 'bresser-eu', name: 'Bresser Spezial Astro 25x70',
    price: 125, currency: 'EUR', currencySymbol: '€', starsPrice: 12500, category: 'binocular',
    description: '25x70 astronomy binoculars built for the night sky. Big objectives and high power reveal clusters, nebulae and lunar detail.',
    image: 'https://www.bresser.com/media/bf/5b/94/1644259097/0114125_M1_v0719.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-spezial-astro-25x70-binoculars-0114125',
  },
  {
    id: 'bres-natgeo-explorer-8x42', dealerId: 'bresser-eu', name: 'National Geographic Explorer 8x42',
    price: 89, currency: 'EUR', currencySymbol: '€', starsPrice: 8900, category: 'binocular',
    description: '8x42 all-purpose roof binoculars. A bright, forgiving exit pupil makes them comfortable for long sweeps of the Milky Way.',
    image: 'https://www.bresser.com/media/1b/89/7c/1761053604/12364_M_01_v1025_.jpg',
    externalUrl: 'https://www.bresser.com/p/national-geographic-explorer-8x42-binoculars-12364',
  },
  {
    id: 'bres-natgeo-10x25-pocket', dealerId: 'bresser-eu', name: 'National Geographic 10x25 Pocket',
    price: 34.90, currency: 'EUR', currencySymbol: '€', starsPrice: 3490, category: 'binocular',
    description: '10x25 pocket binoculars that fold flat for a jacket pocket. A grab-anywhere companion for casual sky and landscape views.',
    image: 'https://www.bresser.com/media/d3/53/1c/1760524873/9025200_M_1_v1025.jpg',
    externalUrl: 'https://www.bresser.com/p/national-geographic-10x25-pocket-binoculars-9025200',
  },
  {
    id: 'bres-pirsch-10x50', dealerId: 'bresser-eu', name: 'Bresser Pirsch 10x50 (Phase Coating)',
    price: 249, currency: 'EUR', currencySymbol: '€', starsPrice: 24900, category: 'binocular',
    description: '10x50 phase-coated roof binoculars, fully waterproof. Bright 50mm optics and crisp contrast for serious binocular astronomy.',
    image: 'https://www.bresser.com/media/c8/35/7c/1691066616/1721050_M_1.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-pirsch-10x50-binoculars-with-phase-coating-1721050',
  },
  {
    id: 'bres-condor-10x42', dealerId: 'bresser-eu', name: 'Bresser Condor 10x42 (UR Coating)',
    price: 149, currency: 'EUR', currencySymbol: '€', starsPrice: 14900, category: 'binocular',
    description: '10x42 roof binoculars with UR multi-coating and nitrogen filling. Sharp, weatherproof and a strong daytime-to-dusk all-rounder.',
    image: 'https://www.bresser.com/media/3f/55/f5/1644311560/1821843_M_1_v0418.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-condor-10x42-binoculars-with-ur-coating-1821043',
  },
  {
    id: 'bres-nightexplorer-15x70', dealerId: 'bresser-eu', name: 'Bresser NightExplorer 15x70',
    price: 499, currency: 'EUR', currencySymbol: '€', starsPrice: 49900, category: 'binocular',
    description: '15x70 astronomy binoculars built for the dark. High power and big objectives bring out faint clusters and nebulae; tripod-ready.',
    image: 'https://www.bresser.com/media/d2/c0/e6/1644314802/9621601_M_1_v0321.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-nightexplorer-15x70-astronomy-binoculars-9621601',
  },
  {
    id: 'bres-nautic-7x50', dealerId: 'bresser-eu', name: 'Bresser Nautic 7x50 Gen. II Marine',
    price: 265, currency: 'EUR', currencySymbol: '€', starsPrice: 26500, category: 'binocular',
    description: '7x50 marine binoculars with a wide field and big exit pupil. The bright, steady view also makes them a fine wide-field sky tool.',
    image: 'https://www.bresser.com/media/95/37/4e/1736003062/1866840_M_01_v1224.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-nautic-7x50-gen.-ii-marine-binoculars-1866840',
  },
  {
    id: 'bres-spezial-astro-20x80', dealerId: 'bresser-eu', name: 'Bresser Spezial-Astro 20x80 Porro',
    price: 159.90, currency: 'EUR', currencySymbol: '€', starsPrice: 15990, category: 'binocular',
    description: '20x80 giant Porro binoculars for deep-sky scanning. Large 80mm objectives pull faint targets from the night; tripod recommended.',
    image: 'https://www.bresser.com/media/41/21/3e/1644318872/1552081_M_1_v0319.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-spezial-astro-20x80-porro-binoculars-1552081',
  },
  {
    id: 'bres-zoomar-8-22x50', dealerId: 'bresser-eu', name: 'Bresser Zoomar 8-22x50 Zoom',
    price: 129.90, currency: 'EUR', currencySymbol: '€', starsPrice: 12990, category: 'binocular',
    description: '8-22x zoom binoculars with 50mm objectives. Flexible magnification for everything from wide star fields to lunar close-ups.',
    image: 'https://www.bresser.com/media/3f/85/d4/1742300443/15027_M_01_v0824.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-zoomar-8-22x50-zoom-binoculars-15027',
  },
  {
    id: 'bres-corvette-10x42', dealerId: 'bresser-eu', name: 'Bresser Corvette 10x42 (Nitrogen-Filled)',
    price: 109, currency: 'EUR', currencySymbol: '€', starsPrice: 10900, category: 'binocular',
    description: '10x42 nitrogen-filled, waterproof roof binoculars. A rugged, fog-proof everyday pair that doubles nicely for the night sky.',
    image: 'https://www.bresser.com/media/e7/19/e2/1685447366/1441043_Amazon_M_1.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-corvette-10x42-binoculars-nitrogen-filled-1441043',
  },
  {
    id: 'bres-travel-8x42', dealerId: 'bresser-eu', name: 'Bresser Travel 8x42',
    price: 79, currency: 'EUR', currencySymbol: '€', starsPrice: 7900, category: 'binocular',
    description: '8x42 lightweight travel binoculars. A bright, comfortable wide field that packs down for trips to dark-sky sites.',
    image: 'https://www.bresser.com/media/37/34/25/1727858248/14948_M_01_v0924.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-binoculars-travel-8x42-14948',
  },
  {
    id: 'bres-hunter-10x50', dealerId: 'bresser-eu', name: 'Bresser Hunter 10x50',
    price: 54.90, currency: 'EUR', currencySymbol: '€', starsPrice: 5490, category: 'binocular',
    description: '10x50 Porro binoculars with big light-gathering objectives. A budget-friendly way into handheld and tripod sky viewing.',
    image: 'https://www.bresser.com/media/1c/e2/14/1678100736/1151050_M1_v032023.jpg',
    externalUrl: 'https://www.bresser.com/p/bresser-hunter-10x50-binoculars-1151050',
  },
  {
    id: 'bres-natgeo-trueview-10x42', dealerId: 'bresser-eu', name: 'National Geographic Trueview NG 10x42',
    price: 129, currency: 'EUR', currencySymbol: '€', starsPrice: 12900, category: 'binocular',
    description: '10x42 open-bridge roof binoculars. Light, ergonomic and sharp — an easy-to-hold pair for both wildlife and stargazing.',
    image: 'https://www.bresser.com/media/c2/0f/8c/1761749632/9676202_M_1_v1025.jpg',
    externalUrl: 'https://www.bresser.com/p/national-geographic-trueview-ng-10x42-binoculars-with-special-open-bridge-9676202',
  },

  // ── Levenhuk (EU) — catalogue top-up ──
  {
    id: 'lev-skyline-travel-50', dealerId: 'levenhuk-eu', name: 'Levenhuk Skyline Travel 50',
    price: 79, currency: 'EUR', currencySymbol: '€', starsPrice: 7900, category: 'telescope',
    description: '50mm travel refractor with eyepieces, Barlow, diagonal and a backpack. Magnifies up to 135x — a packable first scope.',
    image: 'https://levenhuk.com/upload/iblock/34f/6vl5b8dbemt5nz9vc4b33ay9irfzg0qh/levenhuk-telescope-skyline-travel-50_Zgb13gR.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/telescopes/levenhuk-skyline-travel-50-telescope/',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-skyline-base-80t', dealerId: 'levenhuk-eu', name: 'Levenhuk Skyline BASE 80T',
    price: 129, currency: 'EUR', currencySymbol: '€', starsPrice: 12900, category: 'telescope',
    description: '80mm refractor, 500mm focal length on a tripod with finderscope and diagonal. A bright, easy beginner instrument.',
    image: 'https://levenhuk.com/upload/iblock/979/f0nm4tu2ifemkhj1zx76i5lmg0xznj5d/72850_levenhuk-telescope-skyline-base-80t_00.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/telescopes/levenhuk-skyline-base-80t-telescope/',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-skyline-plus-80s', dealerId: 'levenhuk-eu', name: 'Levenhuk Skyline PLUS 80S',
    price: 159, currency: 'EUR', currencySymbol: '€', starsPrice: 15900, category: 'telescope',
    description: '76mm Newtonian reflector, 700mm focal length on an equatorial mount with 2x Barlow. Tuned for deep-sky observing.',
    image: 'https://levenhuk.com/upload/iblock/ece/l1josuzhkt70o718laf3qmgx3muso3hq/73803_levenhuk-telescope-skyline-plus-80s_00.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/telescopes/levenhuk-skyline-plus-80s-telescope/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-skyline-base-60t', dealerId: 'levenhuk-eu', name: 'Levenhuk Skyline BASE 60T',
    price: 109, currency: 'EUR', currencySymbol: '€', starsPrice: 10900, category: 'telescope',
    description: '60mm refractor on a full tripod with finderscope and two eyepieces. A simple, reliable scope for first nights out.',
    image: 'https://levenhuk.com/upload/iblock/bfe/0lpvzjgb4tlvkix3iwbn54mv1gavo82b/72847_levenhuk-telescope-skyline-base-60t_00.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/telescopes/levenhuk-skyline-base-60t-telescope/',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'lev-strike-1000-pro', dealerId: 'levenhuk-eu', name: 'Levenhuk Strike 1000 PRO',
    price: 399, currency: 'EUR', currencySymbol: '€', starsPrice: 39900, category: 'telescope',
    description: '102mm refractor kit, 1000mm focal length, with a rich accessory bundle, case and guidebook. A complete enthusiast package.',
    image: 'https://levenhuk.com/upload/iblock/c91/v2mf4204c455ec9cnqkv6bb6xkjwnq3u/levenhuk-strike-1000-pro_U6OE0do.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/telescopes/levenhuk-strike-1000-pro-telescope/',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-skyline-plus-115s', dealerId: 'levenhuk-eu', name: 'Levenhuk Skyline PLUS 115S',
    price: 219, currency: 'EUR', currencySymbol: '€', starsPrice: 21900, category: 'telescope',
    description: '115mm Newtonian reflector on an equatorial mount. Solid aperture for resolving clusters, nebulae and lunar detail.',
    image: 'https://levenhuk.com/upload/iblock/ab0/k4c4tp8uaim5ks559nyvt8khlw8ag4sl/74374_levenhuk-telescope-skyline-plus-115s_00.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/telescopes/levenhuk-skyline-plus-115s-telescope/',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'lev-karma-pro-10x50', dealerId: 'levenhuk-eu', name: 'Levenhuk Karma PRO 10x50',
    price: 119, currency: 'EUR', currencySymbol: '€', starsPrice: 11900, category: 'binocular',
    description: '10x50 Porro binoculars with multi-coated optics and a wide field. Bright 50mm objectives make them a strong astro starter.',
    image: 'https://levenhuk.com/upload/iblock/a13/s5bv80fsdz7u2e7c34cdnghnmmx1fgiz/67699_levenhuk-karma-pro-10x50-binoculars_00.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/binoculars/levenhuk-karma-pro-10x50/',
  },
  {
    id: 'lev-karma-pro-8x32', dealerId: 'levenhuk-eu', name: 'Levenhuk Karma PRO 8x32',
    price: 99, currency: 'EUR', currencySymbol: '€', starsPrice: 9900, category: 'binocular',
    description: '8x32 compact Porro binoculars. Light and easy to hold steady, with a roomy field for sweeping the Milky Way.',
    image: 'https://levenhuk.com/upload/iblock/a3b/e60d0e1eedzk4qop9dsuwby62yhuxvlz/67703_levenhuk-karma-pro-8x32-binoculars_00.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/binoculars/levenhuk-karma-pro-8x32/',
  },
  {
    id: 'lev-atom-10x25', dealerId: 'levenhuk-eu', name: 'Levenhuk Atom 10x25',
    price: 35, currency: 'EUR', currencySymbol: '€', starsPrice: 3500, category: 'binocular',
    description: '10x25 pocket roof binoculars. They fold to palm size and slip into any bag — a handy grab-and-go for casual sky scanning.',
    image: 'https://levenhuk.com/upload/iblock/b95/126idjv0brwl2tdea2hgbm9u5c4apzhm/67676_levenhuk-atom-10x25-binoculars_00.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/binoculars/levenhuk-atom-10x25-binoculars/',
  },
  {
    id: 'lev-atom-8x21', dealerId: 'levenhuk-eu', name: 'Levenhuk Atom 8x21',
    price: 29, currency: 'EUR', currencySymbol: '€', starsPrice: 2900, category: 'binocular',
    description: '8x21 ultra-compact binoculars for kids and travel. Featherweight and simple, with bright enough optics for the bigger sky sights.',
    image: 'https://levenhuk.com/upload/iblock/7f4/0907wlhlo0zsmha9fa6ah52zbxo6h2w2/67675_levenhuk-atom-8x21-binoculars_00.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/binoculars/levenhuk-atom-8x21-binoculars/',
  },
  {
    id: 'lev-nitro-ed-10x42', dealerId: 'levenhuk-eu', name: 'Levenhuk Nitro ED 10x42',
    price: 199, currency: 'EUR', currencySymbol: '€', starsPrice: 19900, category: 'binocular',
    description: '10x42 ED-glass roof binoculars, nitrogen-filled and waterproof. Low-dispersion optics deliver crisp, high-contrast views.',
    image: 'https://levenhuk.com/upload/iblock/240/yz25z6yan3naih4yhhq793ir1tcfny2c/81942_levenhuk-nitro-ed-10x42-binoculars_00.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/binoculars/levenhuk-nitro-ed-10x42-binoculars/',
  },
  {
    id: 'lev-atom-10-30x50', dealerId: 'levenhuk-eu', name: 'Levenhuk Atom 10-30x50 Zoom',
    price: 65, currency: 'EUR', currencySymbol: '€', starsPrice: 6500, category: 'binocular',
    description: '10-30x zoom binoculars with 50mm objectives. Crank up the power for the Moon, then back off for comfortable wide-field views.',
    image: 'https://levenhuk.com/upload/iblock/e72/f5ovtl3yed9qcs4v2llb9u0onbbigw6m/binoculars-levenhuk-atom-10-30x50_YzKNYSt.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/binoculars/levenhuk-atom-10-30x50-binoculars/',
  },
  {
    id: 'lev-travel-10x40', dealerId: 'levenhuk-eu', name: 'Levenhuk Travel 10x40',
    price: 55, currency: 'EUR', currencySymbol: '€', starsPrice: 5500, category: 'binocular',
    description: '10x40 Porro binoculars in a light, travel-ready body. A versatile, affordable pair for both daytime nature and night skies.',
    image: 'https://levenhuk.com/upload/iblock/ebe/49dyurtsl51wxabfwxacjvotqooc5x6j/79574_levenhuk-travel-10x40-binoculars_00.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/binoculars/levenhuk-travel-10x40-binoculars/',
  },
  {
    id: 'lev-bruno-plus-20x80', dealerId: 'levenhuk-eu', name: 'Levenhuk Bruno PLUS 20x80',
    price: 159, currency: 'EUR', currencySymbol: '€', starsPrice: 15900, category: 'binocular',
    description: '20x80 giant astronomy binoculars with a tripod adapter. Large objectives and high power for deep-sky scanning on a mount.',
    image: 'https://levenhuk.com/upload/iblock/fc7/z4bd7gq85xx77pj3l7nwxwfxtc6lqfku/levenhuk-binoculars-bruno-plus-20-80_kxcnfS7.jpg',
    externalUrl: 'https://www.levenhuk.com/catalogue/binoculars/levenhuk-bruno-plus-20x80-binoculars/',
  },

  // ── Astroman (GE) — catalogue top-up ──
  {
    id: 'astr-astromaster-114eq', dealerId: 'astroman', name: 'Celestron AstroMaster 114EQ',
    price: 1599, currency: 'GEL', currencySymbol: '₾', starsPrice: 159900, category: 'telescope',
    description: '114mm Newtonian reflector on a German equatorial mount with slow-motion controls. Strong all-round views of Moon, planets and clusters.',
    image: 'https://astroman.ge/wp-content/uploads/2026/05/11.jpg',
    externalUrl: 'https://astroman.ge/astromaster-114eq-telescope/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'astr-nexstar-6slt', dealerId: 'astroman', name: 'Celestron NexStar 6SLT',
    price: 5200, currency: 'GEL', currencySymbol: '₾', starsPrice: 520000, category: 'telescope',
    description: '150mm Schmidt-Cassegrain with computerized GoTo and a 4,000+ object database. Compact optics that auto-find and track the sky.',
    image: 'https://astroman.ge/wp-content/uploads/2026/05/%E1%83%91%E1%83%94%E1%83%A5%E1%83%98-02-1-700x700.jpg',
    externalUrl: 'https://astroman.ge/nexstar-6slt-computerized-telescope/',
    skillLevel: 'advanced' as const,
  },
  {
    id: 'astr-foreseen-400-70', dealerId: 'astroman', name: 'Foreseen 400/70 Telescope',
    price: 355, currency: 'GEL', currencySymbol: '₾', starsPrice: 35500, category: 'telescope',
    description: '70mm refractor, 400mm focal length — a light, short-tube scope with wide fields. A budget-friendly entry for first observers.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/foreseen-tescope-700x700.webp',
    externalUrl: 'https://astroman.ge/foreseen-400-70-telescope/',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'astr-natgeo-50-600', dealerId: 'astroman', name: 'National Geographic 50/600 AZ',
    price: 532, currency: 'GEL', currencySymbol: '₾', starsPrice: 53200, category: 'telescope',
    description: '50mm alt-azimuth refractor, 600mm focal length. Simple to aim and steady to use — a tidy starter for the Moon and planets.',
    image: 'https://astroman.ge/wp-content/uploads/2022/12/8878721-700x700.jpg',
    externalUrl: 'https://astroman.ge/national-geographic-telescope-2/',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'astr-natgeo-76-350-compact', dealerId: 'astroman', name: 'National Geographic 76/350 Compact',
    price: 310, currency: 'GEL', currencySymbol: '₾', starsPrice: 31000, category: 'telescope',
    description: '76mm compact Newtonian reflector, 350mm focal length. Wide, bright fields in a small body — a great gift scope for young astronomers.',
    image: 'https://astroman.ge/wp-content/uploads/2022/12/3442.jpg',
    externalUrl: 'https://astroman.ge/sabavshvo-teleskopi/',
    beginner: true, skillLevel: 'beginner' as const,
  },
  {
    id: 'astr-bresser-sirius-70-900', dealerId: 'astroman', name: 'Bresser Sirius 70/900 AZ',
    price: 998, currency: 'GEL', currencySymbol: '₾', starsPrice: 99800, category: 'telescope',
    description: '70/900 alt-az refractor with smartphone camera adapter. The long focal length gives steady, high-contrast lunar and planetary views.',
    image: 'https://astroman.ge/wp-content/uploads/2026/06/%E1%83%91%E1%83%94%E1%83%A5%E1%83%98-02-1-700x700.jpg',
    externalUrl: 'https://astroman.ge/bresser-sirius-70-900-az/',
    skillLevel: 'beginner' as const,
  },
  {
    id: 'astr-bresser-automatik-80-400', dealerId: 'astroman', name: 'Bresser Automatik 80/400 GoTo',
    price: 2399, currency: 'GEL', currencySymbol: '₾', starsPrice: 239900, category: 'telescope',
    description: '80mm GoTo refractor, 400mm focal length. Wide-field optics with automated object-finding — point, select and let it slew.',
    image: 'https://astroman.ge/wp-content/uploads/2026/06/%E1%83%91%E1%83%94%E1%83%A5%E1%83%98-02-700x700.jpg',
    externalUrl: 'https://astroman.ge/bresser-automatik-80-400-goto/',
    skillLevel: 'intermediate' as const,
  },
  {
    id: 'astr-natgeo-76-350-kit', dealerId: 'astroman', name: 'National Geographic 76/350 + Solar Filter + Adapter',
    price: 659, currency: 'GEL', currencySymbol: '₾', starsPrice: 65900, category: 'telescope',
    description: '76/350 reflector bundled with a solar filter and smartphone adapter. Safe daytime Sun viewing plus easy phone astrophotography.',
    image: 'https://astroman.ge/wp-content/uploads/2022/09/National-Geographic-700x700.webp',
    externalUrl: 'https://astroman.ge/national-geographic/',
    beginner: true, skillLevel: 'beginner' as const,
  },
]

// Editorially curated rails. Kept as id sets (not per-product literals) so the
// picks live in one place and read like a storefront merchandising decision.
// Every dealer/region the storefront serves is represented; regions with no
// hand-pick (Europe accessories/eyepieces) fall back to a derived list on the
// page so a rail is never empty.
const FEATURED_IDS = new Set<string>([
  // Astroman (Caucasus — default region)
  'scope-celestron-70az', 'scope-starsense-dx6', 'scope-nexstar-90slt',
  // Celestron (North America)
  'cel-nexstar8se', 'cel-starsense-dx130', 'cel-skymaster-15x70',
  // Levenhuk / Bresser (Europe)
  'lev-plus130', 'lev-blitz114', 'lev-plus120',
])

const RECOMMENDED_IDS = new Set<string>([
  // Astroman
  'astr-eyepiece-set', 'astr-bino-8x42', 'astr-cosmonaut-moon-lamp',
  // Celestron
  'cel-xcel-7mm', 'cel-zoom-eyepiece', 'cel-nature-dx-8x42',
])

// Editorial ratings for prominently merchandised gear (featured + recommended
// + a few flagships). The catalog has no live review system yet, so these are
// curated placeholders, intentionally scoped to the cards that surface them.
const RATINGS: Record<string, { rating: number; reviews: number }> = {
  'scope-celestron-70az': { rating: 4.8, reviews: 214 },
  'scope-starsense-dx6': { rating: 4.8, reviews: 275 },
  'scope-nexstar-90slt': { rating: 4.7, reviews: 156 },
  'cel-nexstar8se': { rating: 4.9, reviews: 312 },
  'cel-nexstar6se': { rating: 4.9, reviews: 287 },
  'cel-starsense-dx130': { rating: 4.8, reviews: 198 },
  'cel-skymaster-15x70': { rating: 4.7, reviews: 189 },
  'cel-skymaster-25x70': { rating: 4.7, reviews: 142 },
  'cel-nature-dx-8x42': { rating: 4.6, reviews: 96 },
  'cel-xcel-7mm': { rating: 4.7, reviews: 88 },
  'cel-zoom-eyepiece': { rating: 4.6, reviews: 174 },
  'lev-plus130': { rating: 4.8, reviews: 121 },
  'lev-blitz114': { rating: 4.6, reviews: 84 },
  'lev-plus120': { rating: 4.7, reviews: 73 },
  'astr-eyepiece-set': { rating: 4.6, reviews: 41 },
  'astr-bino-8x42': { rating: 4.7, reviews: 58 },
  'astr-cosmonaut-moon-lamp': { rating: 4.8, reviews: 63 },
}

function withMarketplaceStarsPrice(p: Product): Product {
  const featured = FEATURED_IDS.has(p.id) || undefined
  const recommended = RECOMMENDED_IDS.has(p.id) || undefined
  const r = RATINGS[p.id]
  const extra = { featured, recommended, rating: r?.rating, reviews: r?.reviews }
  if (p.kind === 'stars-only') return { ...p, ...extra }
  return {
    ...p,
    starsPrice: computeMarketplaceStarsPrice(p.price, p.currency),
    ...extra,
  }
}

// Global fallback: 2 telescopes each from Astroman, Celestron, and Levenhuk
function buildGlobalFallback(): Product[] {
  const ids = ['astroman', 'celestron-us', 'levenhuk-eu', 'bresser-eu']
  return ids.flatMap((id) =>
    PRODUCTS.filter((p) => p.dealerId === id && p.category === 'telescope')
      .sort((a, b) => a.price - b.price)
      .slice(0, 2)
  ).map(withMarketplaceStarsPrice)
}

export const GLOBAL_FALLBACK = buildGlobalFallback()

export function getDealersByRegion(region: Region): Dealer[] {
  if (region === 'global') return DEALERS
  if (region === 'asia') return DEALERS.filter((d) => d.id === 'astroman')
  if (region === 'south_america') return DEALERS.filter((d) => d.id === 'celestron-us')
  return DEALERS.filter((d) => d.region === region)
}

export function getProductsByRegion(region: Region): Product[] {
  if (region === 'global') return GLOBAL_FALLBACK
  if (region === 'asia') {
    return PRODUCTS.filter((p) => p.dealerId === 'astroman').map(withMarketplaceStarsPrice)
  }
  if (region === 'south_america') {
    return PRODUCTS.filter((p) => p.dealerId === 'celestron-us').map(withMarketplaceStarsPrice)
  }
  const dealerIds = getDealersByRegion(region).map((d) => d.id)
  return PRODUCTS.filter((p) => dealerIds.includes(p.dealerId)).map(withMarketplaceStarsPrice)
}

export function getDealerById(id: string): Dealer | undefined {
  return DEALERS.find((d) => d.id === id)
}

export function getProductById(id: string): Product | undefined {
  const p = PRODUCTS.find((x) => x.id === id)
  return p ? withMarketplaceStarsPrice(p) : undefined
}

export function getProductsByDealer(dealerId: string): Product[] {
  return PRODUCTS.filter((p) => p.dealerId === dealerId).map(withMarketplaceStarsPrice)
}

export function getAllDealers(): Dealer[] {
  return DEALERS
}

const USD_PER_EUR = 1.08

export function priceToSol(
  price: number,
  currency: string,
  solPerGEL: number,
  solPriceUsd: number,
): number {
  if (currency === 'GEL' && solPerGEL > 0) return price * solPerGEL
  if (currency === 'USD' && solPriceUsd > 0) return price / solPriceUsd
  if (currency === 'EUR' && solPriceUsd > 0) return (price * USD_PER_EUR) / solPriceUsd
  return 0
}

/**
 * USD equivalent of a product price. GEL is bridged via the live SOL rate
 * (GEL → SOL → USD) so the dollar figure tracks the same source as the SOL
 * price. Lets non-Georgian buyers read GEL-listed gear at a glance.
 */
export function priceToUsd(
  price: number,
  currency: string,
  solPerGEL: number,
  solPriceUsd: number,
): number {
  if (currency === 'USD') return price
  if (currency === 'EUR') return price * USD_PER_EUR
  if (currency === 'GEL' && solPerGEL > 0 && solPriceUsd > 0) return price * solPerGEL * solPriceUsd
  return 0
}
