import { NextRequest, NextResponse } from 'next/server';
import { PrivyClient } from '@privy-io/server-auth';
import { eq } from 'drizzle-orm';
import { getDb } from '@/lib/db';
import { natalCharts } from '@/lib/schema';
import { generateStarMapSVG } from '@/lib/astrology/star-map-generator';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

let _privy: PrivyClient | null = null;
function getPrivy(): PrivyClient {
  if (!_privy) {
    _privy = new PrivyClient(
      process.env.NEXT_PUBLIC_PRIVY_APP_ID!,
      process.env.PRIVY_APP_SECRET!,
    );
  }
  return _privy;
}

export async function GET(req: NextRequest) {
  const authHeader = req.headers.get('authorization');
  const token = authHeader?.startsWith('Bearer ') ? authHeader.slice(7) : null;
  if (!token) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    await getPrivy().verifyAuthToken(token);
  } catch {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const chartId = req.nextUrl.searchParams.get('chartId');
    if (!chartId) {
      return NextResponse.json({ error: 'Missing chartId' }, { status: 400 });
    }

    const db = getDb();
    if (!db) {
      return NextResponse.json({ error: 'Database unavailable' }, { status: 503 });
    }

    const chart = await db.query.natalCharts.findFirst({
      where: eq(natalCharts.id, chartId),
    });

    if (!chart) {
      return NextResponse.json({ error: 'Chart not found' }, { status: 404 });
    }

    const svg = generateStarMapSVG({
      width: 800,
      height: 800,
      lat: chart.lat,
      lon: chart.lon,
      date: chart.birthDate,
      birthTime: chart.birthTime,
      sunSign: chart.sunSign as any,
      name: chart.name,
    });

    // Return as HTML with embedded SVG for display/printing
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${chart.name}'s Personal Star Map</title>
    <style>
        body {
            margin: 0;
            padding: 20px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: #0A1735;
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
        }
        .container {
            max-width: 900px;
            text-align: center;
        }
        svg {
            max-width: 100%;
            height: auto;
            box-shadow: 0 8px 32px rgba(0,0,0,0.3);
            border-radius: 12px;
        }
        .metadata {
            margin-top: 30px;
            color: #FFB347;
            font-size: 14px;
            line-height: 1.6;
        }
        .download-btn {
            display: inline-block;
            margin-top: 20px;
            padding: 12px 24px;
            background: linear-gradient(135deg, #5EEAD4 0%, #06B6D4 100%);
            color: #0A1735;
            border: none;
            border-radius: 8px;
            font-weight: 600;
            cursor: pointer;
            text-decoration: none;
            font-size: 14px;
        }
        .download-btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(94, 234, 212, 0.3);
        }
        @media print {
            body { padding: 0; background: white; }
            .metadata, .download-btn { display: none; }
            svg { box-shadow: none; }
        }
    </style>
</head>
<body>
    <div class="container">
        ${svg}
        <div class="metadata">
            <p style="font-size: 16px; margin-bottom: 10px;">✦ ${chart.name}'s Personal Star Map ✦</p>
            <p>Born ${chart.birthDate.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })} at ${chart.birthTime}</p>
            <p>In ${chart.locationName}</p>
            <p style="margin-top: 20px; opacity: 0.7;">A keepsake of your birth moment, personalized with the stars that witnessed your arrival.</p>
            <p style="opacity: 0.5; margin-top: 10px;">Generated by Stellar Astrology — www.stellarr.club</p>
        </div>
        <button class="download-btn" onclick="window.print()">Print or Save as PDF</button>
    </div>
</body>
</html>`;

    return new Response(html, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'public, max-age=86400',
      },
    });
  } catch (err) {
    console.error('[Astrology] Star map generation failed:', err);
    return NextResponse.json({ error: 'Failed to generate star map' }, { status: 500 });
  }
}
