import type { Category, Market, NewsItem } from './types';

export const TODAY = new Date('2026-05-23T00:00:00Z');

export const STORAGE_KEY = 'stellar.markets.bets.v2';

export const CATEGORIES: { key: Category | 'all'; label: string; emoji: string }[] = [
  { key: 'all',       label: 'All',          emoji: '✦' },
  { key: 'sky',       label: 'Sky',          emoji: '🌌' },
  { key: 'solar',     label: 'Solar',        emoji: '☀' },
  { key: 'meteor',    label: 'Meteors',      emoji: '☄' },
  { key: 'comet',     label: 'Comets',       emoji: '🪐' },
  { key: 'mission',   label: 'Missions',     emoji: '🚀' },
  { key: 'discovery', label: 'Discoveries',  emoji: '🔭' },
  { key: 'weather',   label: 'Weather',      emoji: '⛅' },
  { key: 'nature',    label: 'Earth',        emoji: '🌍' },
  { key: 'crypto',    label: 'Crypto',       emoji: '₿' },
  { key: 'sports',    label: 'Sports',       emoji: '⚽' },
  { key: 'tech',      label: 'Tech',         emoji: '⚙' },
];

export const MARKETS: Market[] = [
  // SKY
  {
    id: 'sky-saturn-ringplane',
    category: 'sky',
    title: 'Saturn rings reach max tilt by Sep 21 opposition',
    blurb: 'Tilt angle ≥ 1.7° as Saturn reaches 2026 opposition.',
    resolvesAt: '2026-09-21',
    yes: 0.78,
    trend: 0.06,
    volume: 4250,
    image: '/images/markets/sky-007-xclass-flare-window.jpg',
    oracle: 'JPL ephemeris',
  },
  {
    id: 'sky-jupiter-bright',
    category: 'sky',
    title: 'Jupiter reaches magnitude −2.8 or brighter on opposition',
    blurb: 'Naked-eye check on Aug 6 from Bortle 4 site.',
    resolvesAt: '2026-08-07',
    yes: 0.62,
    trend: 0.03,
    volume: 2980,
    image: '/images/markets/sky-005-mclass-flare-judging.jpg',
    oracle: 'AAVSO',
  },
  {
    id: 'sky-iss-pass',
    category: 'sky',
    title: 'Visible ISS pass over Tbilisi this week',
    blurb: 'Pass duration ≥ 4 min, max elevation ≥ 30°.',
    resolvesAt: '2026-05-28',
    yes: 0.91,
    trend: 0.04,
    volume: 1820,
    image: '/images/markets/mission-004-starship-orbit.jpg',
    oracle: 'Heavens-Above',
  },
  {
    id: 'sky-falcon9-cadence',
    category: 'sky',
    title: 'Falcon 9 logs ≥ 12 launches in June',
    blurb: 'Cadence currently averaging 2.6 launches per week.',
    resolvesAt: '2026-07-01',
    yes: 0.71,
    trend: 0.08,
    volume: 3140,
    image: '/images/markets/sky-004-falcon9-cadence.jpg',
    oracle: 'SpaceX manifest',
  },
  {
    id: 'sky-moon-supermoon',
    category: 'sky',
    title: 'Nov 14 supermoon is the largest of 2026',
    blurb: 'Perigee distance ≤ 356,800 km.',
    resolvesAt: '2026-11-15',
    yes: 0.94,
    trend: 0.01,
    volume: 1670,
    image: '/images/markets/sky-002-eta-aquariids-zhr.jpg',
    oracle: 'JPL ephemeris',
  },
  {
    id: 'sky-iss-transit-sun',
    category: 'sky',
    title: 'ISS transits the solar disc visible from Europe in June',
    blurb: 'Predictable but narrow band — ground track 5–10 km wide.',
    resolvesAt: '2026-07-01',
    yes: 0.66,
    trend: 0.05,
    volume: 1340,
    image: '/images/markets/mission-004-starship-orbit.jpg',
    oracle: 'Heavens-Above',
  },
  {
    id: 'sky-conj-mars-jupiter',
    category: 'sky',
    title: 'Mars–Jupiter pass within 0.5° in August',
    blurb: 'Tight conjunction in Cancer — finder-scope worthy.',
    resolvesAt: '2026-08-15',
    yes: 0.81,
    trend: 0.12,
    volume: 2010,
    image: '/images/markets/sky-007-xclass-flare-window.jpg',
    oracle: 'JPL ephemeris',
  },
  {
    id: 'sky-mercury-elongation',
    category: 'sky',
    title: 'Mercury reaches greatest eastern elongation > 23°',
    blurb: 'Best evening apparition of 2026 in late July.',
    resolvesAt: '2026-07-30',
    yes: 0.88,
    trend: 0.02,
    volume: 720,
    image: '/images/markets/sky-005-mclass-flare-judging.jpg',
    oracle: 'JPL ephemeris',
  },

  // SOLAR
  {
    id: 'solar-xflare-jul',
    category: 'solar',
    title: 'X-class solar flare before Jul 1',
    blurb: 'Cycle 25 still active. Last X-flare logged May 9.',
    resolvesAt: '2026-07-01',
    yes: 0.55,
    trend: 0.18,
    volume: 6710,
    image: '/images/markets/solar-001-xflare-may.jpg',
    oracle: 'NOAA SWPC',
  },
  {
    id: 'solar-aurora-45n',
    category: 'solar',
    title: 'Aurora visible south of 45°N before solstice',
    blurb: 'Kp ≥ 7 storm reaching mid-latitudes.',
    resolvesAt: '2026-06-21',
    yes: 0.34,
    trend: 0.09,
    volume: 3050,
    image: '/images/markets/solar-003-aurora-45n.jpg',
    oracle: 'NOAA SWPC + reports',
  },
  {
    id: 'solar-kp7',
    category: 'solar',
    title: 'Kp index ≥ 7 in the next 30 days',
    blurb: 'Three-hour Kp index from any station, NOAA-confirmed.',
    resolvesAt: '2026-06-20',
    yes: 0.41,
    trend: 0.07,
    volume: 2110,
    image: '/images/markets/sky-006-kp5-geomagnetic.jpg',
    oracle: 'NOAA SWPC',
  },
  {
    id: 'solar-mclass-judging',
    category: 'solar',
    title: 'M-class flare during judging week (May 23 – Jun 1)',
    blurb: 'Active region AR3895 climbed to βγδ classification.',
    resolvesAt: '2026-06-01',
    yes: 0.83,
    trend: 0.15,
    volume: 1990,
    image: '/images/markets/sky-005-mclass-flare-judging.jpg',
    oracle: 'NOAA SWPC',
  },
  {
    id: 'solar-cycle-peak',
    category: 'solar',
    title: 'NOAA declares Cycle 25 peak month before Sep 30',
    blurb: 'Smoothed sunspot number tracking — currently 156.',
    resolvesAt: '2026-09-30',
    yes: 0.59,
    trend: 0.11,
    volume: 2640,
    image: '/images/markets/solar-005-f107-decline.jpg',
    oracle: 'NOAA SWPC monthly report',
  },
  {
    id: 'solar-cme-direct',
    category: 'solar',
    title: 'Earth-directed CME above 1000 km/s in June',
    blurb: 'Halo CME plus G3 watch in NOAA forecast.',
    resolvesAt: '2026-07-01',
    yes: 0.43,
    trend: -0.04,
    volume: 1810,
    image: '/images/markets/solar-004-x5-2026.jpg',
    oracle: 'NOAA SWPC',
  },
  {
    id: 'solar-x5-class',
    category: 'solar',
    title: 'X5-class or stronger flare in 2026',
    blurb: 'X5+ events are roughly 3× per cycle peak.',
    resolvesAt: '2026-12-31',
    yes: 0.78,
    trend: 0.04,
    volume: 3270,
    image: '/images/markets/solar-004-x5-2026.jpg',
    oracle: 'NOAA SWPC',
  },

  // METEOR
  {
    id: 'meteor-bootids',
    category: 'meteor',
    title: 'June Boötids ZHR > 50 this year',
    blurb: 'Historical outburst window — 2025 returned ZHR 23.',
    resolvesAt: '2026-07-05',
    yes: 0.22,
    trend: -0.05,
    volume: 1280,
    image: '/images/markets/meteor-005-outburst.jpg',
    oracle: 'IMO global flux',
  },
  {
    id: 'meteor-perseids',
    category: 'meteor',
    title: 'Perseids peak ZHR ≥ 90 in August',
    blurb: 'Moon at 26% — favorable conditions for the 2026 peak.',
    resolvesAt: '2026-08-13',
    yes: 0.68,
    trend: 0.07,
    volume: 5340,
    image: '/images/markets/meteor-003-perseids-zhr.jpg',
    oracle: 'IMO global flux',
  },
  {
    id: 'meteor-fireball-caucasus',
    category: 'meteor',
    title: 'Fireball ≥ mag −6 reported over Caucasus before Aug 1',
    blurb: 'AMS / IMO confirmed report with ≥ 5 witnesses.',
    resolvesAt: '2026-08-01',
    yes: 0.29,
    trend: 0.02,
    volume: 940,
    image: '/images/markets/meteor-004-fireball-april.jpg',
    oracle: 'AMS / IMO',
  },
  {
    id: 'meteor-eta-aquariids-replay',
    category: 'meteor',
    title: 'Eta Aquariids late peak (May 28) ZHR ≥ 30',
    blurb: 'Halley dust trail — late stragglers possible.',
    resolvesAt: '2026-05-30',
    yes: 0.37,
    trend: -0.08,
    volume: 880,
    image: '/images/markets/meteor-002-eta-aquariids-zhr.jpg',
    oracle: 'IMO global flux',
  },
  {
    id: 'meteor-tau-herculids',
    category: 'meteor',
    title: 'Tau Herculids ZHR > 30 during May 30 peak',
    blurb: '2022 outburst gave ZHR 25 — return appearance plausible.',
    resolvesAt: '2026-06-01',
    yes: 0.31,
    trend: 0.04,
    volume: 1110,
    image: '/images/markets/meteor-005-outburst.jpg',
    oracle: 'IMO global flux',
  },
  {
    id: 'meteor-leonid-storm',
    category: 'meteor',
    title: 'Leonid storm (ZHR > 200) in November',
    blurb: 'No outburst predicted by IMO — long-shot contrarian play.',
    resolvesAt: '2026-11-18',
    yes: 0.06,
    trend: 0.01,
    volume: 1480,
    image: '/images/markets/meteor-005-outburst.jpg',
    oracle: 'IMO global flux',
  },
  {
    id: 'meteor-geminids',
    category: 'meteor',
    title: 'Geminids peak ZHR ≥ 120 on Dec 14',
    blurb: '3200 Phaethon parent body — reliable storm-class shower.',
    resolvesAt: '2026-12-15',
    yes: 0.74,
    trend: 0.03,
    volume: 2860,
    image: '/images/markets/meteor-003-perseids-zhr.jpg',
    oracle: 'IMO global flux',
  },

  // COMET
  {
    id: 'comet-r3-naked-eye',
    category: 'comet',
    title: 'C/2025 R3 brighter than magnitude 6.0 in June',
    blurb: 'Currently mag 6.8 — favorable orbit, dust-rich.',
    resolvesAt: '2026-07-01',
    yes: 0.57,
    trend: 0.21,
    volume: 2160,
    image: '/images/markets/comet-001-c2025r3-nakedeye.jpg',
    oracle: 'COBS database',
  },
  {
    id: 'comet-new-2026',
    category: 'comet',
    title: 'New naked-eye comet discovered in 2026',
    blurb: 'Magnitude < 6.0 at any point during the year.',
    resolvesAt: '2026-12-31',
    yes: 0.38,
    trend: 0.06,
    volume: 1730,
    image: '/images/markets/comet-002-new-discovery.jpg',
    oracle: 'IAU MPEC',
  },
  {
    id: 'comet-a1-survives',
    category: 'comet',
    title: 'C/2026 A1 survives perihelion intact',
    blurb: 'Perihelion July 12 at 0.31 AU — sungrazer-class.',
    resolvesAt: '2026-07-15',
    yes: 0.47,
    trend: -0.10,
    volume: 1990,
    image: '/images/markets/comet-005-c2026a1-survives.jpg',
    oracle: 'SOHO/JPL',
  },
  {
    id: 'comet-rubin-nea',
    category: 'comet',
    title: 'Rubin Observatory flags a hazardous NEA in 2026',
    blurb: 'First-light survey already finding new bodies weekly.',
    resolvesAt: '2026-12-31',
    yes: 0.59,
    trend: 0.04,
    volume: 1430,
    image: '/images/markets/comet-003-rubin-nea.jpg',
    oracle: 'MPC NEA confirmed',
  },
  {
    id: 'comet-tianwen2-sample',
    category: 'comet',
    title: 'Tianwen-2 returns asteroid sample by year end',
    blurb: 'Sample-return to Kamoʻoalewa — landing Q4.',
    resolvesAt: '2026-12-31',
    yes: 0.51,
    trend: 0.02,
    volume: 1180,
    image: '/images/markets/comet-004-tianwen2-sample.jpg',
    oracle: 'CNSA confirmed return',
  },
  {
    id: 'comet-r3-tail-degrees',
    category: 'comet',
    title: 'C/2025 R3 tail exceeds 5° at peak brightness',
    blurb: 'Dust-rich comet, low perihelion — long tail probable.',
    resolvesAt: '2026-07-15',
    yes: 0.42,
    trend: 0.14,
    volume: 1320,
    image: '/images/markets/comet-001-c2025r3-nakedeye.jpg',
    oracle: 'COBS + amateur reports',
  },
  {
    id: 'comet-pan-starrs-disco',
    category: 'comet',
    title: 'Pan-STARRS discovers ≥ 25 new comets in 2026',
    blurb: 'Survey at full sensitivity — currently averaging 22/year.',
    resolvesAt: '2026-12-31',
    yes: 0.66,
    trend: 0.05,
    volume: 770,
    image: '/images/markets/comet-002-new-discovery.jpg',
    oracle: 'MPC bulletin',
  },

  // MISSION
  {
    id: 'mission-artemis-ii',
    category: 'mission',
    title: 'Artemis II launches in 2026',
    blurb: 'Crewed lunar flyby — schedule slipped to late Q3.',
    resolvesAt: '2026-12-31',
    yes: 0.44,
    trend: -0.12,
    volume: 8120,
    image: '/images/markets/mission-001-artemis2-safe.jpg',
    oracle: 'NASA launch manifest',
  },
  {
    id: 'mission-starship-orbit',
    category: 'mission',
    title: 'Starship reaches stable orbit before Jul 1',
    blurb: 'Last test cleared boost-back but ditched short.',
    resolvesAt: '2026-07-01',
    yes: 0.36,
    trend: 0.09,
    volume: 4570,
    image: '/images/markets/mission-004-starship-orbit.jpg',
    oracle: 'SpaceX webcast',
  },
  {
    id: 'mission-roman',
    category: 'mission',
    title: 'Roman Space Telescope launches in 2026',
    blurb: 'Falcon Heavy slot tentatively booked for November.',
    resolvesAt: '2026-12-31',
    yes: 0.51,
    trend: 0.03,
    volume: 2840,
    image: '/images/markets/mission-002-roman-2026.jpg',
    oracle: 'NASA launch manifest',
  },
  {
    id: 'mission-change7',
    category: 'mission',
    title: "Chang'e-7 returns samples by Sep 30",
    blurb: 'Lunar south-pole sample-return — launch window open.',
    resolvesAt: '2026-09-30',
    yes: 0.40,
    trend: -0.06,
    volume: 1560,
    image: '/images/markets/mission-003-change7.jpg',
    oracle: 'CNSA / press release',
  },
  {
    id: 'mission-plato-ready',
    category: 'mission',
    title: 'ESA PLATO declared launch-ready before Dec 31',
    blurb: 'Exoplanet hunter — payload integration in Toulouse.',
    resolvesAt: '2026-12-31',
    yes: 0.46,
    trend: 0.04,
    volume: 1340,
    image: '/images/markets/mission-005-plato.jpg',
    oracle: 'ESA mission page',
  },
  {
    id: 'mission-starliner-crew',
    category: 'mission',
    title: 'Boeing Starliner flies crew rotation before Dec',
    blurb: 'Second crewed flight after the 2024 stranding ordeal.',
    resolvesAt: '2026-12-01',
    yes: 0.32,
    trend: 0.05,
    volume: 2150,
    image: '/images/markets/mission-001-artemis2-safe.jpg',
    oracle: 'NASA / Boeing announcement',
  },
  {
    id: 'mission-dragon-private',
    category: 'mission',
    title: 'Polaris Dawn 2 or equivalent private Dragon flies Q3',
    blurb: 'Isaacman-class private spaceflight on the manifest.',
    resolvesAt: '2026-10-01',
    yes: 0.48,
    trend: 0.07,
    volume: 1180,
    image: '/images/markets/mission-004-starship-orbit.jpg',
    oracle: 'SpaceX manifest',
  },
  {
    id: 'mission-europa-clipper',
    category: 'mission',
    title: 'Europa Clipper completes its Mars gravity-assist nominally',
    blurb: 'March 2025 flyby data still propagating — fine-tune burn in Q3.',
    resolvesAt: '2026-08-15',
    yes: 0.87,
    trend: 0.02,
    volume: 1640,
    image: '/images/markets/mission-002-roman-2026.jpg',
    oracle: 'NASA JPL telemetry',
  },
  {
    id: 'mission-jaxa-mmx',
    category: 'mission',
    title: 'JAXA MMX launches to Phobos before year end',
    blurb: 'H3 launch slot held for September.',
    resolvesAt: '2026-12-31',
    yes: 0.41,
    trend: -0.03,
    volume: 720,
    image: '/images/markets/mission-005-plato.jpg',
    oracle: 'JAXA mission page',
  },
  {
    id: 'mission-spacex-starbase-flights',
    category: 'mission',
    title: 'SpaceX flies ≥ 4 Starship integrated tests in 2026',
    blurb: 'Booster rate accelerating — current pace 3.',
    resolvesAt: '2026-12-31',
    yes: 0.61,
    trend: 0.13,
    volume: 3960,
    image: '/images/markets/mission-004-starship-orbit.jpg',
    oracle: 'SpaceX webcast',
  },

  // DISCOVERY
  {
    id: 'discovery-jwst-bio',
    category: 'discovery',
    title: 'JWST confirms biosignature on an exoplanet in 2026',
    blurb: 'K2-18b reanalysis + LHS 1140 b campaign in flight.',
    resolvesAt: '2026-12-31',
    yes: 0.14,
    trend: 0.06,
    volume: 9210,
    image: '/images/markets/discovery-001-jwst-bio.jpg',
    oracle: 'Peer-reviewed Nature/Science',
  },
  {
    id: 'discovery-ligo-merger',
    category: 'discovery',
    title: 'LIGO/Virgo detect another NS–NS merger by year end',
    blurb: 'Run O5 nominally producing 1 per 6 months.',
    resolvesAt: '2026-12-31',
    yes: 0.66,
    trend: 0.03,
    volume: 1480,
    image: '/images/markets/discovery-003-ligo-nsmerger.jpg',
    oracle: 'LIGO/Virgo GraceDB',
  },
  {
    id: 'discovery-gaia-dr4',
    category: 'discovery',
    title: 'Gaia DR4 data release before Q4',
    blurb: '2 billion stars, full radial-velocity catalogue.',
    resolvesAt: '2026-10-01',
    yes: 0.32,
    trend: -0.07,
    volume: 1010,
    image: '/images/markets/discovery-004-gaia-dr4.jpg',
    oracle: 'ESA Gaia archive',
  },
  {
    id: 'discovery-nobel-cosmo',
    category: 'discovery',
    title: 'Nobel Physics 2026 awarded to cosmology work',
    blurb: 'JWST early-galaxy results are favourites in Stockholm.',
    resolvesAt: '2026-10-15',
    yes: 0.28,
    trend: 0.02,
    volume: 860,
    image: '/images/markets/discovery-002-nobel-cosmo.jpg',
    oracle: 'Nobel committee announcement',
  },
  {
    id: 'discovery-laserseti',
    category: 'discovery',
    title: 'LaserSETI logs a confirmed pulsed candidate',
    blurb: 'Two-station coincidence under 24h verification.',
    resolvesAt: '2026-12-31',
    yes: 0.09,
    trend: 0.01,
    volume: 1620,
    image: '/images/markets/discovery-005-laserseti.jpg',
    oracle: 'SETI Institute press release',
  },
  {
    id: 'discovery-exomoon',
    category: 'discovery',
    title: 'First confirmed exomoon announced in 2026',
    blurb: 'Kepler-1625b and Kepler-1708b candidates under reanalysis.',
    resolvesAt: '2026-12-31',
    yes: 0.18,
    trend: 0.05,
    volume: 2210,
    image: '/images/markets/discovery-001-jwst-bio.jpg',
    oracle: 'Peer-reviewed Nature/Science',
  },
  {
    id: 'discovery-frb-host',
    category: 'discovery',
    title: 'A new FRB localised to its host galaxy in 2026',
    blurb: 'CHIME + DSA-110 averaging ~12 localisations per year.',
    resolvesAt: '2026-12-31',
    yes: 0.84,
    trend: 0.04,
    volume: 920,
    image: '/images/markets/discovery-003-ligo-nsmerger.jpg',
    oracle: 'ATel + peer-reviewed paper',
  },
  {
    id: 'discovery-naked-eye-sn',
    category: 'discovery',
    title: 'A naked-eye supernova in 2026',
    blurb: 'Betelgeuse betting market — last one was 1987A.',
    resolvesAt: '2026-12-31',
    yes: 0.03,
    trend: 0.00,
    volume: 8480,
    image: '/images/markets/discovery-004-gaia-dr4.jpg',
    oracle: 'IAU CBAT announcement',
  },
  {
    id: 'discovery-jwst-redshift-15',
    category: 'discovery',
    title: 'JWST confirms a galaxy at redshift > 15',
    blurb: 'Current record is z = 14.32 (JADES-GS-z14-0).',
    resolvesAt: '2026-12-31',
    yes: 0.39,
    trend: 0.11,
    volume: 1650,
    image: '/images/markets/discovery-001-jwst-bio.jpg',
    oracle: 'Peer-reviewed Nature/Science',
  },

  // CRYPTO
  {
    id: 'crypto-btc-150k',
    category: 'crypto',
    title: 'BTC closes ≥ $150,000 by Aug 1',
    blurb: 'Spot ETF flows positive 7 of last 8 weeks.',
    resolvesAt: '2026-08-01',
    yes: 0.43,
    trend: -0.09,
    volume: 14520,
    image: '/images/markets/crypto-001-btc-100k.jpg',
    oracle: 'Coinbase 23:59 UTC close',
  },
  {
    id: 'crypto-sol-300',
    category: 'crypto',
    title: 'SOL ≥ $300 by Sep 30',
    blurb: 'Network hit 3.2k TPS daily avg last quarter.',
    resolvesAt: '2026-09-30',
    yes: 0.39,
    trend: 0.16,
    volume: 9870,
    image: '/images/markets/crypto-002-sol-300.jpg',
    oracle: 'Coinbase 23:59 UTC close',
  },
  {
    id: 'crypto-eth-flippening',
    category: 'crypto',
    title: 'ETH market cap > BTC at any 23:59 UTC close in 2026',
    blurb: 'Spread currently 2.1× — flippening would be historic.',
    resolvesAt: '2026-12-31',
    yes: 0.07,
    trend: 0.01,
    volume: 4230,
    image: '/images/markets/crypto-003-eth-flippening.jpg',
    oracle: 'CoinGecko close-of-day',
  },
  {
    id: 'crypto-stable-volume',
    category: 'crypto',
    title: 'Stablecoin daily volume > $300B before Q4',
    blurb: 'On-chain settlement up 40% YoY — Solana leads.',
    resolvesAt: '2026-10-01',
    yes: 0.58,
    trend: 0.07,
    volume: 2780,
    image: '/images/markets/crypto-004-stable-volume.png',
    oracle: 'Artemis / DefiLlama',
  },
  {
    id: 'crypto-eth-10k',
    category: 'crypto',
    title: 'ETH ≥ $10,000 by Nov 30',
    blurb: 'Pectra upgrade + ETF momentum priced in.',
    resolvesAt: '2026-11-30',
    yes: 0.29,
    trend: 0.04,
    volume: 6710,
    image: '/images/markets/crypto-003-eth-flippening.jpg',
    oracle: 'Coinbase 23:59 UTC close',
  },
  {
    id: 'crypto-sol-ath',
    category: 'crypto',
    title: 'SOL hits new all-time high in 2026',
    blurb: 'Current ATH $295.83 (Jan 2025).',
    resolvesAt: '2026-12-31',
    yes: 0.62,
    trend: 0.18,
    volume: 5240,
    image: '/images/markets/crypto-002-sol-300.jpg',
    oracle: 'Coinbase 23:59 UTC close',
  },
  {
    id: 'crypto-doge-1',
    category: 'crypto',
    title: 'DOGE > $1 at any 23:59 UTC close in 2026',
    blurb: 'X integration rumors persist — memecoin season open.',
    resolvesAt: '2026-12-31',
    yes: 0.16,
    trend: -0.03,
    volume: 3990,
    image: '/images/markets/crypto-001-btc-100k.jpg',
    oracle: 'Coinbase 23:59 UTC close',
  },
  {
    id: 'crypto-tvl-300b',
    category: 'crypto',
    title: 'Total DeFi TVL > $300B before Q4',
    blurb: 'Currently $204B per DefiLlama — needs +47%.',
    resolvesAt: '2026-10-01',
    yes: 0.33,
    trend: 0.06,
    volume: 1860,
    image: '/images/markets/crypto-004-stable-volume.png',
    oracle: 'DefiLlama snapshot',
  },

  // SPORTS
  {
    id: 'sports-world-cup',
    category: 'sports',
    title: 'France wins 2026 FIFA World Cup',
    blurb: 'Tournament June 11 – July 19, US/CAN/MEX.',
    resolvesAt: '2026-07-19',
    yes: 0.21,
    trend: 0.02,
    volume: 11200,
    image: '/images/markets/sports-003-world-cup-host.jpg',
    oracle: 'FIFA official',
  },
  {
    id: 'sports-nba-finals',
    category: 'sports',
    title: 'Boston Celtics win 2026 NBA Finals',
    blurb: 'Up 2–1 in conference finals as of May 20.',
    resolvesAt: '2026-06-22',
    yes: 0.46,
    trend: 0.08,
    volume: 7340,
    image: '/images/markets/sports-002-nba-finals.jpg',
    oracle: 'NBA official',
  },
  {
    id: 'sports-cl-final',
    category: 'sports',
    title: 'UEFA Champions League final is decided in extra time',
    blurb: 'Munich, May 30 — historical 18% goes past 90.',
    resolvesAt: '2026-05-30',
    yes: 0.24,
    trend: 0.03,
    volume: 5180,
    image: '/images/markets/sports-001-cl-final.jpg',
    oracle: 'UEFA official',
  },
  {
    id: 'sports-f1-driver',
    category: 'sports',
    title: 'Max Verstappen wins 2026 F1 Drivers Championship',
    blurb: 'Currently +37 points clear after Imola.',
    resolvesAt: '2026-11-29',
    yes: 0.62,
    trend: 0.04,
    volume: 4620,
    image: '/images/markets/sports-004-f1-driver.jpg',
    oracle: 'FIA standings',
  },
  {
    id: 'sports-tour-de-france',
    category: 'sports',
    title: 'Tadej Pogačar wins the 2026 Tour de France',
    blurb: 'Defending champion — Vingegaard out injured.',
    resolvesAt: '2026-07-26',
    yes: 0.71,
    trend: 0.06,
    volume: 2960,
    image: '/images/markets/sports-004-f1-driver.jpg',
    oracle: 'ASO official',
  },
  {
    id: 'sports-wimbledon',
    category: 'sports',
    title: 'Carlos Alcaraz wins Wimbledon 2026',
    blurb: 'Defending two-time champion on grass.',
    resolvesAt: '2026-07-12',
    yes: 0.42,
    trend: 0.04,
    volume: 3420,
    image: '/images/markets/sports-001-cl-final.jpg',
    oracle: 'AELTC official',
  },
  {
    id: 'sports-stanley-cup',
    category: 'sports',
    title: 'Edmonton Oilers win 2026 Stanley Cup',
    blurb: 'McDavid drought enters year 9 — final June 5.',
    resolvesAt: '2026-06-30',
    yes: 0.34,
    trend: 0.11,
    volume: 1860,
    image: '/images/markets/sports-002-nba-finals.jpg',
    oracle: 'NHL official',
  },
  {
    id: 'sports-cricket-t20',
    category: 'sports',
    title: 'India wins 2026 T20 World Cup',
    blurb: 'Hosts in India + Sri Lanka, Feb–Mar 2026.',
    resolvesAt: '2026-03-15',
    yes: 0.38,
    trend: 0.05,
    volume: 5210,
    image: '/images/markets/sports-003-world-cup-host.jpg',
    oracle: 'ICC official',
  },

  // TECH
  {
    id: 'tech-gpt5',
    category: 'tech',
    title: 'OpenAI ships GPT-5 publicly by Sep 1',
    blurb: 'Sam Altman teased "next major model" mid-summer.',
    resolvesAt: '2026-09-01',
    yes: 0.52,
    trend: 0.13,
    volume: 6620,
    image: '/images/markets/discovery-005-laserseti.jpg',
    oracle: 'OpenAI blog / pricing page',
  },
  {
    id: 'tech-apple-wwdc',
    category: 'tech',
    title: 'Apple announces AI-first iPhone at WWDC 2026',
    blurb: 'WWDC opens June 8 — rumors of on-device GPT tier.',
    resolvesAt: '2026-06-15',
    yes: 0.61,
    trend: 0.08,
    volume: 4180,
    image: '/images/markets/discovery-002-nobel-cosmo.jpg',
    oracle: 'WWDC keynote',
  },
  {
    id: 'tech-nvidia-stock',
    category: 'tech',
    title: 'NVIDIA market cap > $5T at any 2026 close',
    blurb: 'Currently $3.4T — needs +47% on data-center demand.',
    resolvesAt: '2026-12-31',
    yes: 0.41,
    trend: 0.12,
    volume: 5640,
    image: '/images/markets/discovery-005-laserseti.jpg',
    oracle: 'NASDAQ close',
  },
  {
    id: 'tech-gemini-3',
    category: 'tech',
    title: 'Google ships Gemini 3.0 publicly by Sep 1',
    blurb: 'Gemini 2.5 already in market — 3.0 in internal preview.',
    resolvesAt: '2026-09-01',
    yes: 0.47,
    trend: 0.05,
    volume: 2310,
    image: '/images/markets/discovery-005-laserseti.jpg',
    oracle: 'Google blog announcement',
  },
  {
    id: 'tech-quantum-supremacy',
    category: 'tech',
    title: 'Definitive quantum supremacy demo on commercial problem',
    blurb: 'Google + IBM + IonQ all chasing utility milestone.',
    resolvesAt: '2026-12-31',
    yes: 0.24,
    trend: 0.03,
    volume: 1490,
    image: '/images/markets/discovery-004-gaia-dr4.jpg',
    oracle: 'Peer-reviewed Nature/Science',
  },
  {
    id: 'tech-anthropic-claude-5',
    category: 'tech',
    title: 'Anthropic ships Claude 5 publicly by Aug 1',
    blurb: 'Opus 4.7 currently in production — 5.0 rumored Q3.',
    resolvesAt: '2026-08-01',
    yes: 0.36,
    trend: 0.07,
    volume: 1820,
    image: '/images/markets/discovery-005-laserseti.jpg',
    oracle: 'Anthropic API release',
  },

  // WEATHER
  {
    id: 'weather-tbilisi-clear-week',
    category: 'weather',
    title: '≥ 3 clear nights in Tbilisi this week',
    blurb: 'Cloud cover < 30% between 22:00 and 02:00.',
    resolvesAt: '2026-05-28',
    yes: 0.58,
    trend: 0.10,
    volume: 720,
    image: '/images/markets/weather-001-tbilisi-clear-run.jpg',
    oracle: 'Open-Meteo',
  },
  {
    id: 'weather-perseids-clear',
    category: 'weather',
    title: 'Perseids viewing clear from Caucasus on Aug 12',
    blurb: 'Cloud cover < 40% at observing latitude.',
    resolvesAt: '2026-08-13',
    yes: 0.49,
    trend: 0.02,
    volume: 1830,
    image: '/images/markets/weather-005-perseids-europe.jpg',
    oracle: 'Open-Meteo',
  },
  {
    id: 'weather-tbilisi-warmday',
    category: 'weather',
    title: 'Tbilisi hits ≥ 32°C this week',
    blurb: 'Caucasus heat dome strengthening per ECMWF.',
    resolvesAt: '2026-05-30',
    yes: 0.64,
    trend: 0.18,
    volume: 540,
    image: '/images/markets/weather-001-tbilisi-warm-day.jpg',
    oracle: 'NOAA / Open-Meteo',
  },
  {
    id: 'weather-georgia-bortle2',
    category: 'weather',
    title: 'Bortle 2 night logged from Tusheti this season',
    blurb: 'SQM ≥ 21.7 mag/arcsec² reading verified.',
    resolvesAt: '2026-09-30',
    yes: 0.71,
    trend: 0.06,
    volume: 410,
    image: '/images/markets/weather-004-georgia-bortle2.jpg',
    oracle: 'SQM device upload',
  },
  {
    id: 'weather-tbilisi-100mm',
    category: 'weather',
    title: '≥ 100mm rain falls in Tbilisi in any 7-day window before Aug',
    blurb: 'June convective storms historically deliver 60–90mm.',
    resolvesAt: '2026-08-01',
    yes: 0.31,
    trend: -0.04,
    volume: 380,
    image: '/images/markets/weather-002-tbilisi-may-day-rain.jpg',
    oracle: 'NMG observation',
  },
  {
    id: 'weather-may-snow',
    category: 'weather',
    title: 'Snowfall in Caucasus highlands above 2500m this week',
    blurb: 'Cold front approaching from the Black Sea.',
    resolvesAt: '2026-05-30',
    yes: 0.43,
    trend: -0.09,
    volume: 290,
    image: '/images/markets/weather-003-stockholm-frost.jpg',
    oracle: 'NMG observation',
  },
  {
    id: 'weather-spain-eclipse-aug',
    category: 'weather',
    title: 'Total eclipse path in Spain has < 40% cloud on Aug 12',
    blurb: 'Aug 12, 2026 — first total eclipse over mainland Spain in a century.',
    resolvesAt: '2026-08-13',
    yes: 0.55,
    trend: 0.04,
    volume: 4810,
    image: '/images/markets/weather-002-spain-eclipse.jpg',
    oracle: 'AEMET',
  },

  // NATURE
  {
    id: 'nature-volcanic-eruption',
    category: 'nature',
    title: 'New VEI ≥ 3 volcanic eruption before Aug 1',
    blurb: 'Three candidates trending — Kilauea, Etna, Sakurajima.',
    resolvesAt: '2026-08-01',
    yes: 0.55,
    trend: 0.07,
    volume: 1290,
    image: '/images/markets/natural-003-new-volcanic-eruption.jpg',
    oracle: 'Smithsonian GVP',
  },
  {
    id: 'nature-reykjanes-swarm',
    category: 'nature',
    title: 'Reykjanes peninsula erupts again before Q4',
    blurb: 'Magma chamber refilling — IMO raised alert May 18.',
    resolvesAt: '2026-10-01',
    yes: 0.67,
    trend: 0.22,
    volume: 970,
    image: '/images/markets/natural-006-reykjanes-swarm.jpg',
    oracle: 'Icelandic Met Office',
  },
  {
    id: 'nature-m6-judging',
    category: 'nature',
    title: 'M6.0+ earthquake during judging week',
    blurb: 'USGS background rate ≈ 2.8 per week worldwide.',
    resolvesAt: '2026-06-01',
    yes: 0.83,
    trend: 0.04,
    volume: 1140,
    image: '/images/markets/natural-001-m6-judging-week.jpg',
    oracle: 'USGS catalog',
  },
  {
    id: 'nature-cyclone-named',
    category: 'nature',
    title: 'Named tropical cyclone in Atlantic before Jun 30',
    blurb: 'NHC season opens June 1. Last year had three by July.',
    resolvesAt: '2026-06-30',
    yes: 0.39,
    trend: 0.09,
    volume: 880,
    image: '/images/markets/natural-005-named-tropical-cyclone.jpg',
    oracle: 'NHC public advisory',
  },
  {
    id: 'nature-arctic-ice-min',
    category: 'nature',
    title: 'Arctic sea-ice minimum < 4.0 Mkm² in September',
    blurb: 'Last 5-year average 4.32 Mkm² — warming trend.',
    resolvesAt: '2026-10-01',
    yes: 0.58,
    trend: 0.06,
    volume: 1060,
    image: '/images/markets/natural-004-firms-large-wildfire-us.jpg',
    oracle: 'NSIDC daily index',
  },
  {
    id: 'nature-amazon-low',
    category: 'nature',
    title: 'Amazon river hits new record-low water level in 2026',
    blurb: 'La Niña fading — but 2024–25 drought legacy persists.',
    resolvesAt: '2026-11-30',
    yes: 0.36,
    trend: 0.04,
    volume: 640,
    image: '/images/markets/natural-004-firms-large-wildfire-us.jpg',
    oracle: 'Brazil ANA gauge',
  },
  {
    id: 'nature-wildfire-us',
    category: 'nature',
    title: '> 4 Mha burned by US wildfires in 2026',
    blurb: 'NIFC tracker on pace for above-average year.',
    resolvesAt: '2026-12-31',
    yes: 0.61,
    trend: 0.08,
    volume: 1170,
    image: '/images/markets/natural-004-firms-large-wildfire-us.jpg',
    oracle: 'NIFC fire stats',
  },
  {
    id: 'nature-tbilisi-quake',
    category: 'nature',
    title: 'M4.0+ earthquake within 100 km of Tbilisi this year',
    blurb: 'Caucasus is seismically active — last M4 was Nov 2025.',
    resolvesAt: '2026-12-31',
    yes: 0.74,
    trend: 0.03,
    volume: 510,
    image: '/images/markets/natural-002-m5-near-tbilisi.jpg',
    oracle: 'USGS catalog',
  },
];

export const NEWS: NewsItem[] = [
  {
    id: 'news-1',
    source: 'NOAA SWPC',
    headline: 'AR3895 region grows to βγδ classification — flare watch upgraded',
    marketId: 'solar-xflare-jul',
    hoursAgo: 4,
  },
  {
    id: 'news-2',
    source: 'IMO',
    headline: 'Eta Aquariids late peak (May 28) — Halley trail still active',
    marketId: 'meteor-eta-aquariids-replay',
    hoursAgo: 9,
  },
  {
    id: 'news-3',
    source: 'NASA',
    headline: 'Artemis II static-fire passes; integrated test on schedule',
    marketId: 'mission-artemis-ii',
    hoursAgo: 16,
  },
  {
    id: 'news-4',
    source: 'COBS',
    headline: 'C/2025 R3 brightens to mag 6.5 — naked-eye window opening',
    marketId: 'comet-r3-naked-eye',
    hoursAgo: 22,
  },
  {
    id: 'news-5',
    source: 'Icelandic Met Office',
    headline: 'Reykjanes magma intrusion accelerates — eruption likely',
    marketId: 'nature-reykjanes-swarm',
    hoursAgo: 31,
  },
  {
    id: 'news-6',
    source: 'Open-Meteo',
    headline: 'Caucasus high-pressure ridge: 3 clear nights forecast over Tbilisi',
    marketId: 'weather-tbilisi-clear-week',
    hoursAgo: 38,
  },
];

export const FAKE_BETTORS = [
  'astra_42', 'nika.eth', 'kalliope', 'm31_observer', 'photon7', 'sgr_a',
  'tycho', 'lyra_n', 'cosmonshop', 'darkfield', 'kepler9', 'sirius_a',
  'orion.gz', 'm42', 'ngc_628', 'rho.oph', 'caph', 'antares',
  'helios.sol', 'crab_neb', 'pulsar.b1919', 'andromeda9', 'h_alpha',
  'pleiades7', 'corvus_g', 'iota_uma', 'zeta_oph', 'lambda_sco',
  'epsilon_eri', 'tau_ceti', '47.uma', 'beta_pic', 'aurigae',
  'cygnus_x1', 'altair_a', 'wolf359', 'proxima_b',
];
