// Real per-market hero images (Polymarket-style). Generated by image-fetch agent.
// Sources: Wikimedia Commons, NASA, ESA, USGS public-domain photographs.
export const MARKET_IMAGES: Record<string, string> = {
  // V2 catalogue
  "meteor-001-lyrids-zhr": "/images/markets/meteor-001-lyrids-zhr.jpg",
  "meteor-002-eta-aquariids-zhr": "/images/markets/meteor-002-eta-aquariids-zhr.jpg",
  "meteor-003-perseids-zhr": "/images/markets/meteor-003-perseids-zhr.jpg",
  "meteor-004-fireball-april": "/images/markets/meteor-004-fireball-april.jpg",
  "meteor-005-outburst": "/images/markets/meteor-005-outburst.jpg",
  "solar-001-xflare-may": "/images/markets/solar-001-xflare-may.jpg",
  "solar-002-kp7-june": "/images/markets/solar-002-kp7-june.jpg",
  "solar-003-aurora-45n": "/images/markets/solar-003-aurora-45n.jpg",
  "solar-004-x5-2026": "/images/markets/solar-004-x5-2026.jpg",
  "solar-005-f107-decline": "/images/markets/solar-005-f107-decline.jpg",
  "mission-001-artemis2-safe": "/images/markets/mission-001-artemis2-safe.jpg",
  "mission-002-roman-2026": "/images/markets/mission-002-roman-2026.jpg",
  "mission-003-change7": "/images/markets/mission-003-change7.jpg",
  "mission-004-starship-orbit": "/images/markets/mission-004-starship-orbit.jpg",
  "mission-005-plato": "/images/markets/mission-005-plato.jpg",
  "comet-001-c2025r3-nakedeye": "/images/markets/comet-001-c2025r3-nakedeye.jpg",
  "comet-002-new-discovery": "/images/markets/comet-002-new-discovery.jpg",
  "comet-003-rubin-nea": "/images/markets/comet-003-rubin-nea.jpg",
  "comet-004-tianwen2-sample": "/images/markets/comet-004-tianwen2-sample.jpg",
  "comet-005-c2026a1-survives": "/images/markets/comet-005-c2026a1-survives.jpg",
  "discovery-001-jwst-bio": "/images/markets/discovery-001-jwst-bio.jpg",
  "discovery-002-nobel-cosmo": "/images/markets/discovery-002-nobel-cosmo.jpg",
  "discovery-003-ligo-nsmerger": "/images/markets/discovery-003-ligo-nsmerger.jpg",
  "discovery-004-gaia-dr4": "/images/markets/discovery-004-gaia-dr4.jpg",
  "discovery-005-laserseti": "/images/markets/discovery-005-laserseti.jpg",
  "weather-001-tbilisi-clear-run": "/images/markets/weather-001-tbilisi-clear-run.jpg",
  "weather-002-spain-eclipse": "/images/markets/weather-002-spain-eclipse.jpg",
  "weather-003-tbilisi-lyrids": "/images/markets/weather-003-tbilisi-lyrids.jpg",
  "weather-004-georgia-bortle2": "/images/markets/weather-004-georgia-bortle2.jpg",
  "weather-005-perseids-europe": "/images/markets/weather-005-perseids-europe.jpg",

  // V1 catalogue (sky-*)
  "sky-001-lyrids-zhr": "/images/markets/sky-001-lyrids-zhr.jpg",
  "sky-002-eta-aquariids-zhr": "/images/markets/sky-002-eta-aquariids-zhr.jpg",
  "sky-003-vandenberg-april22": "/images/markets/sky-003-vandenberg-april22.jpg",
  "sky-004-falcon9-cadence": "/images/markets/sky-004-falcon9-cadence.jpg",
  "sky-005-mclass-flare-judging": "/images/markets/sky-005-mclass-flare-judging.jpg",
  "sky-006-kp5-geomagnetic": "/images/markets/sky-006-kp5-geomagnetic.jpg",
  "sky-007-xclass-flare-window": "/images/markets/sky-007-xclass-flare-window.jpg",

  // V1 weather + natural
  "weather-001-tbilisi-warm-day": "/images/markets/weather-001-tbilisi-warm-day.jpg",
  "weather-002-tbilisi-may-day-rain": "/images/markets/weather-002-tbilisi-may-day-rain.jpg",
  "weather-003-stockholm-frost": "/images/markets/weather-003-stockholm-frost.jpg",
  "weather-004-london-heathrow-rain": "/images/markets/weather-004-london-heathrow-rain.jpg",
  "weather-005-tbilisi-clear-eta": "/images/markets/weather-005-tbilisi-clear-eta.jpg",
  "weather-006-tbilisi-dry-week": "/images/markets/weather-006-tbilisi-dry-week.jpg",
  "weather-007-nyc-warm-may7": "/images/markets/weather-007-nyc-warm-may7.jpg",
  "natural-001-m6-judging-week": "/images/markets/natural-001-m6-judging-week.jpg",
  "natural-002-m5-near-tbilisi": "/images/markets/natural-002-m5-near-tbilisi.jpg",
  "natural-003-new-volcanic-eruption": "/images/markets/natural-003-new-volcanic-eruption.jpg",
  "natural-004-firms-large-wildfire-us": "/images/markets/natural-004-firms-large-wildfire-us.jpg",
  "natural-005-named-tropical-cyclone": "/images/markets/natural-005-named-tropical-cyclone.jpg",
  "natural-006-reykjanes-swarm": "/images/markets/natural-006-reykjanes-swarm.jpg",

  // Crypto
  "crypto-001-btc-100k":      "/images/markets/crypto-001-btc-100k.jpg",
  "crypto-002-sol-300":       "/images/markets/crypto-002-sol-300.jpg",
  "crypto-003-eth-flippening":"/images/markets/crypto-003-eth-flippening.jpg",
  "crypto-004-stable-volume": "/images/markets/crypto-004-stable-volume.png",

  // Sports
  "sports-001-cl-final":      "/images/markets/sports-001-cl-final.jpg",
  "sports-002-nba-finals":    "/images/markets/sports-002-nba-finals.jpg",
  "sports-003-world-cup-host":"/images/markets/sports-003-world-cup-host.jpg",
  "sports-004-f1-driver":     "/images/markets/sports-004-f1-driver.jpg",
};

export function marketImage(id: string): string | null {
  return MARKET_IMAGES[id] ?? null;
}
