import { getVisiblePlanets } from '@/lib/planets';
import { getZodiacEmoji } from './natal-chart';
import type { ZodiacSign } from './natal-chart';

interface StarMapConfig {
  width: number;
  height: number;
  lat: number;
  lon: number;
  date: Date;
  birthTime: string;
  sunSign: ZodiacSign;
  name: string;
}

export function generateStarMapSVG(config: StarMapConfig): string {
  const { width, height, lat, lon, date, birthTime, sunSign, name } = config;

  const cx = width / 2;
  const cy = height / 2;
  const radius = Math.min(width, height) / 2 - 40;

  let svg = `<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">
    <!-- Background -->
    <defs>
      <radialGradient id="skyGradient">
        <stop offset="0%" style="stop-color:#0A1735;stop-opacity:1" />
        <stop offset="100%" style="stop-color:#1a2f5a;stop-opacity:1" />
      </radialGradient>
    </defs>
    <rect width="${width}" height="${height}" fill="url(#skyGradient)" />

    <!-- Outer circle -->
    <circle cx="${cx}" cy="${cy}" r="${radius}" fill="none" stroke="rgba(255,179,71,0.3)" stroke-width="2" />

    <!-- Zodiac ring -->
    <circle cx="${cx}" cy="${cy}" r="${radius + 30}" fill="none" stroke="rgba(94,234,212,0.2)" stroke-width="1" />
  `;

  // Add zodiac signs around the circle
  const zodiacSigns = [
    'aries',
    'taurus',
    'gemini',
    'cancer',
    'leo',
    'virgo',
    'libra',
    'scorpio',
    'sagittarius',
    'capricorn',
    'aquarius',
    'pisces',
  ];

  for (let i = 0; i < 12; i++) {
    const angle = (i * 30) * (Math.PI / 180);
    const x = cx + (radius + 45) * Math.cos(angle - Math.PI / 2);
    const y = cy + (radius + 45) * Math.sin(angle - Math.PI / 2);

    const sign = zodiacSigns[i] as ZodiacSign;
    const emoji = getZodiacEmoji(sign);

    svg += `<text x="${x}" y="${y}" text-anchor="middle" dominant-baseline="middle" font-size="16" fill="rgba(255,179,71,0.6)">${emoji}</text>`;
  }

  // Add planets
  const planets = getVisiblePlanets(lat, lon, date);
  const [birthHour] = birthTime.split(':').map(Number);

  for (const planet of planets) {
    if (!planet.visible) continue;

    const angle = (planet.azimuth * Math.PI) / 180;
    const altRadius = (planet.altitude / 90) * radius;
    const x = cx + altRadius * Math.cos(angle - Math.PI / 2);
    const y = cy + altRadius * Math.sin(angle - Math.PI / 2);

    const size = planet.key === 'sun' || planet.key === 'moon' ? 8 : 4;
    const color = planet.key === 'sun' ? 'rgba(255,200,87,1)' : planet.key === 'moon' ? 'rgba(200,220,255,1)' : 'rgba(200,200,200,0.8)';

    svg += `<circle cx="${x}" cy="${y}" r="${size}" fill="${color}" />`;
  }

  // Add title and metadata
  const dateStr = date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  svg += `
    <text x="${cx}" y="30" text-anchor="middle" font-size="24" font-weight="bold" fill="#FFB347">${name}</text>
    <text x="${cx}" y="60" text-anchor="middle" font-size="14" fill="rgba(255,179,71,0.7)">Born ${dateStr} at ${birthTime}</text>
    <text x="${cx}" y="${height - 20}" text-anchor="middle" font-size="12" fill="rgba(94,234,212,0.6)">Sun in ${getZodiacEmoji(sunSign as ZodiacSign)} — Your Personal Star Map</text>
  </svg>`;

  return svg;
}

export function generateStarMapHTML(config: StarMapConfig): string {
  const svg = generateStarMapSVG(config);

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${config.name}'s Personal Star Map</title>
    <style>
        body {
            margin: 0;
            padding: 20px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: #0A1735;
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
        }
        .container {
            max-width: 800px;
            text-align: center;
        }
        ${svg}
        .metadata {
            margin-top: 20px;
            color: #FFB347;
            font-size: 14px;
        }
        @media print {
            body { padding: 0; background: white; }
            .metadata { display: none; }
        }
    </style>
</head>
<body>
    <div class="container">
        ${svg}
        <div class="metadata">
            <p>A keepsake of your birth moment, personalized with the stars that witnessed your arrival.</p>
            <p>Generated by Stellar Astrology — www.stellarr.club</p>
        </div>
    </div>
</body>
</html>`;
}
